import 'package:get/get.dart';

class Language extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {

      "selected_file": "Selected File",
      "select_format": "Select Format",
      "convert": "Convert",
      "converting": "Converting...",
      "please_select_format_first": "Please select a format first",
      "conversion_failed": "Conversion Failed",
      "ok": "OK",

      "word": "Word",
      "excel": "Excel",
      "powerpoint": "PowerPoint",
      "image": "Image",

      "error_excel_not_implemented": "Excel conversion not implemented",

      "am": "AM",
      "pm": "PM",

      "convert_pdf_format": "Convert PDF Format",
      "convert_pdf_description": "Easily convert PDFs to various formats while retaining their quality, resolution and clarity.",

      "click_to_choose_pdf": "Click to choose PDF file",
      "next": "Next",
      "error_selecting_pdf": "Error selecting PDF",
      "please_select_pdf_first": "Please select a PDF file first",

      "edit": "Edit",
      "failed_to_open_document": "Failed to open document",
      "file_deleted_successfully": "File deleted successfully",
      "generated_document": "Generated Document",

      "original": "Original",
      "cool_tone": "Cool Tone",
      "warm_tone": "Warm Tone",
      "grayscale": "Grayscale",
      "blue_light": "Blue Light",
      "sepia": "Sepia",
      "soft_pastel": "Soft Pastel",

      "crop_document": "Crop Document",
      "done": "Done",
      "cancel": "Cancel",
      "retake": "Retake",
      "filters": "Filters",
      "crop": "Crop",
      "rotate": "Rotate",

      "failed_to_crop_image": "Failed to crop image",
      "failed_to_create_document": "Failed to create document",
      "error_cropping_image": "Error cropping image",
      "error_rotating_image": "Error rotating image",
      "error_applying_filter": "Error applying filter",

      "rearrange_results": "Rearrange Results",
      "processing_document": "Processing document...",
      "reading_pages": "Reading document pages...",
      "rearranging_pdf": "Rearranging PDF pages...",
      "rearranging_docx": "Rearranging document pages...",
      "creating_new_file": "Creating new document...",
      "rearrange_success": "Document successfully rearranged!",
      "error_occurred": "An error occurred",
      "try_again": "Try again",
      "no_app_to_open": "No application found to open this file type",
      "permission_denied": "Permission denied to open the file",
      "file_deleted": "File successfully deleted!",
      "file_renamed": "File successfully renamed!",
      "rearranged_files": "Rearranged files",
      "bytes": "bytes",
      "invalid_page_index": "Invalid page index",
      "no_pages_found": "No pages found in document",
      "empty_file": "Created file is empty",
      "file_not_created": "Output file was not successfully created",
      "file_not_exist": "File does not exist",

      "error_processing_file": "Error processing file",
      "page_number": "Page",
      "selected_file": "Selected file",
      "loading_pdf_previews": "Loading PDF previews...",
      "rearrange": "Rearrange",

      "rearrange_files": "Rearrange Files",
      "rearrange_pages_in_files": "Rearrange Pages in Files",
      "select_file": "Select File",
      "rearrange_file": "Rearrange File",
      'rearrange_file_desc': 'Easily drag and reorder PDF pages to organize your document effortlessly.',

      "failed_to_save_file": "Failed to save file",
      "file_renamed_successfully": "File renamed successfully",
      "error_renaming_file": "Error renaming file",
      "no_pages_selected": "No pages selected",
      "no_document_available_to_open": "No document available to open",
      "file_not_found": "File not found",
      "cannot_open_file": "Unable to open the file",
      "zip_file_message": "This is a ZIP file. You may need a ZIP extractor app to view its contents.",
      "error_opening_document": "Error opening document",
      "error_during_deletion": "Error during deletion",
      "processing_generic_document": "Processing document...",
      "error_encountered_fallback": "Error encountered, using fallback method...",
      "creating_pdf_selected_pages": "Creating PDF with selected pages...",
      "pdf_created_successfully": "PDF with selected pages created successfully!",
      "splitting_docx_files": "Splitting DOCX into separate files...",
      "creating_zip_archive": "Creating ZIP archive...",
      "zip_created_successfully": "ZIP archive created successfully!",
      "error_saving_original": "Error occurred. Saving the original file instead...",

      'edit_files': 'Edit Files',
      'edit_files_description': 'Make changes to your images easily. Upload and modify multiple images for a seamless experience.',
      'choose_images': 'Choose Images',
      'click_to_choose_images_from_gallery': 'Click to choose images from gallery',

      'error_selecting_images': 'Error selecting images',
      'error_capturing_document': 'Error capturing document',
      'error_processing_files': 'Error processing files',
      'please_select_at_least_one_image': 'Please select at least one image',
      'image_removed_successfully': 'Image removed successfully',

      'merged_pdf_file': 'Merge PDF File:',
      'merge_results': 'Merge Results',
      'error_opening_file': 'Error opening file',
      'file_not_found_or_not_processed': 'File not found or not yet processed',
      'merge_completed_successfully': 'PDF files merged successfully!',

      //merge
      'merge_pdfs': 'Merge PDFs',
      'total_files': 'Total Files',
      'merge_pdf_files': 'Merge PDF Files',
      'merge_file_desc':
      'Effortlessly merge PDF Files for easier sharing, storage, and organization.',
      'select_files': 'Select Files',
      'click_files': 'Click to add PDF files',
      'merge_files': 'Merge Files',
      'please_two_select': 'Please select at least 2 PDF files',
      'selected_files': 'Selected Files',
      'page_order': 'Page order',
      'please_select_pdf_only': 'Please select PDF files only',
      'error_selecting_pdfs': 'Error selecting PDFs',
      'failed_to_merge': 'Failed to merge PDFs',
      'pdf_merger': 'PDF Merger',
      'choose_pdf_files': 'Choose PDF Files',
      'add_more_files': 'Add More Files',
      'remove': 'Remove',
      'reorder': 'Reorder',
      'processing': 'Processing...',
      'merge_complete': 'Merge Complete',
      'file_size': 'File Size',
      'Total_pages': 'Total Pages',
      'drag_to_reorder': 'Drag to reorder',
      'no_files_selected': 'No files selected',
      'maximum_files_limit_reached': 'Maximum files limit reached',
      'file_format_not_supported': 'File format not supported',
      'merge_successful': 'Merge successful',
      'save_merged_file': 'Save merged file',


      'press_again_to_exit': 'Press again to exit',

      // Menu items
      "rename": "Rename",
      "share": "Share",
      "delete": "Delete",

      // Error messages
      "error_sharing_file": "Error sharing file",
      "error_deleting_file": "Error deleting file",

      // Dialog titles and content
      "delete_file": "Delete File",
      "delete_file_confirmation": "Are you sure you want to delete this file?",
      "rename_file": "Rename File",


      // Share content
      "sharing_document_from_ocr_tool": "Sharing document from OCR Tool",
      "document_from_ocr_tool": "Document from OCR Tool",

      // Validation messages
      "please_enter_valid_name": "Please enter a valid name",
      "file_name_already_exists": "File name already exists.",

      'drag_drop': 'Drag & Drop or click to choose file',

      "error_creating_zip_file": "Error creating ZIP file",
      "file_saved_successfully": "File saved successfully",
      "failed_to_save_file_generic": "Failed to save file",
      "no_files_to_save": "No files to save",
      "all_files_saved_as_zip": "All files saved as ZIP",
      "compression_summary": "Compression Summary",
      "file_not_compressed_message": "File is not able to compress because it already compressed or not supported.",
      "saving": "Saving...",

      "compress_file": "Compress File",
      "reduce_file_size": "Reduce File Size",
      "reduce_file_size_description": "Reduce the size of PDFs, documents, and images while preserving original quality.",
      "compression_quality": "Compression Quality",
      "compressing": "Compressing...",
      "compress": "Compress",
      "maximum_compression": "Maximum\nCompression",
      "maximum_quality": "Maximum\nQuality",
      "invalid_file_formats": "Invalid file formats",
      "files_must_be_at_least_mb": "Files must be at least 1 MB",
      "duplicate_files_skipped": "Duplicate files skipped",
      "no_valid_files_selected": "No valid files selected",
      "some_files_were_skipped": "Some files were skipped",
      "duplicates": "duplicate(s)",
      "rejected_too_small": "rejected (too small)",
      "invalid_formats": "invalid format(s)",
      "error_selecting_files": "Error selecting files",
      "please_select_at_least_one_file": "Please select at least one file first",
      "error_compressing_files": "Error compressing files",
      "too_small": "too small",
      "kilobytes": "KB",
      "megabytes": "MB",
      "file_size_format": "{size} {unit}",

      // File Transfer Screen
      'file_transfer': 'File Transfer',
      'easy_transfer_file': 'Easy File Transfer',
      'easy_file_transfer_description': 'Transfer files instantly while keeping quality, resolution, and clarity intact.',
      'choose_file': 'Choose File',
      'extract_text': 'Extract Text',
      'extract_text_from_files': 'Extract Text From Files',
      'explore_tools': 'Explore Tools',
      'extract_text_description': 'Seamlessly extract text copy from multiple images or documents instantly with enhanced accuracy.',

      'scan_new': 'Scan New',
      'completed': 'Completed!',
      'please_wait': 'Please wait!',
      'file_name': 'File Name',
      'single': 'Single',
      'batch': 'Batch',
      'camera_permission_required': 'Camera permission is required to use the scanner',
      'no_cameras_found': 'No cameras found on device',
      'camera_initialization_failed': 'Camera initialization failed',
      'camera_permission_not_granted': 'Camera permission not granted',
      'grant_camera_permission': 'Grant Camera Permission',
      'initializing_camera': 'Initializing camera...',
      'failed_to_toggle_flash': 'Failed to toggle flash',

      'extracted_text_file': 'Extracted Text File:',
      'no_file_available': 'No file available',
      'extracted_text': 'Extracted Text:',
      'error_saving_file': 'Error saving file',
      'could_not_open_file': 'Could not open file',
      'text_copied_to_clipboard': 'Text copied to clipboard',
      'error_copying_text': 'Error copying text',

      'select_at_least_one_image': 'Please select at least one image',
      'no_text_in_images': 'No text could be found in the selected images. Try images with clearer text.',
      'error_processing_images': 'Error processing images: @error',
      'image_header': '--- Image @number ---',
      'error_picking_images': 'Error picking images: @error',
      'error_preprocessing_image': 'Error preprocessing image: @error',
      'error_in_ocr': 'Error in OCR: @error',
      'error_deleting_temp_file': 'Error deleting temp file: @error',

      'click_to_choose_files': 'Click to choose files',
      'pdf_scanner': 'PDF Scanner',
      'create_your_cv': 'Create Your CV',
      'ocr': 'OCR',
      'merge_file': 'Merge File',
      'edit_file': 'Edit File',
      'split_file': 'Split File',
      'convert_options': 'Convert Options',
      'convert_pdf': 'Convert PDF',
      'convert_image': 'Convert Image',
      'recents': 'Recents',
      'see_all': 'See All',

      'split': 'Split',
      'split_pages': 'Split Pages In File',
      'split_description': 'Effortlessly separate pages from files while keeping everything clear and intact.',
      'split_document': 'Split Document',
      'save': 'Save',

      'notifications_alerts': 'Notifications & Alerts',
      'support_feedback': 'Support & Feedback',
      'privacy_policy': 'Privacy Policy',
      'rate_us': 'Rate Us',
      'general': 'General',
      'language': 'Language',
      'confidential_documents': 'Confidential Documents',
      'code_recovery_options': 'Code Recovery Options',
      'email': 'Email',
      'phone_number': 'Phone Number',
      'settings': 'Settings',

      'please_select_one_page': 'Please select at least one page',
      'split_file_progress_screen': 'Split File:',
      'compressed': 'Compressed Files:',
      'space_saved': 'Space Saved:',
      'total_reduction': 'Total Reductions:',
      'compress_results': 'Compression Results',
      'file_delete': 'File deleted successfully',
      'error_opening_doc': 'Error opening document',
      'drag_and_drop': 'Drag & Drop or click to choose file',
      'select_only_pdf': 'Please select only PDF, DOC or DOCX files',
      'rearrange_file_pages': 'Rearrange Pages In Files',
      'rearrange_file_description': 'Effortlessly drag and reorder PDF pages to organize your document effortlessly.',
      'error': 'Error occurred',
      'processing_doc': 'Processing document...',
      'file_does_not_exist': 'File does not exist',
      'file_empty': 'File is empty',
      'opening_file': 'Opening file:',
      'rearrange_pages': 'Rearrange Pages',
      'selected': 'Selected:',
      'easy_file_transfer': 'Easy Transfer File',

      //new Settings Secreen lines
      'notification_enabled': 'Notifications Enabled Successfully',
      'notification_permission': 'Notification permission denied',
      'notification_error': 'Error enabling notifications',
      'notification_disabled': 'Notifications Disabled',
      'notification_error_disabled': 'Error disabling notifications',
      'notifications_and_alerts': 'Notifications & Alerts',
      'support_and_feedback': 'Support & Feedback',
      'privacy_and_policy': 'Privacy Policy',
      //'rate_us': 'Rate Us',
      //'share': 'Share',
      //'general': 'General',
      'confidential_document': 'Confidential Documents',
      //'code_recovery_options': 'Code Recovery Options',
      //'email': 'Email',
      //'settings': 'Settings',

      // Email Recovery Screen
      'enter_your_email': 'Enter your\nEmail',
      'please_enter_your': 'Please enter your ',
      'enter': 'Enter',
      "email_verify": "Email Verify",
      "enter_email_label": "Enter email*",
      "email_hint": "abc@abc.com",
      "enter_email_error": "Please enter your email",
      "valid_email_error": "Please enter a valid email address",
      //"enter_your_email": "Enter Your Email",

      //Phone Recovery Screen
      "phone_verify": "Phone verify",
      "enter_your_phone": "Enter your\nPhone number",
      //"please_enter_your": "Please enter your ",
      //"phone_number": "phone number",
      "enter_mobile_label": "Enter mobile no.*",
      "mobile_hint": "01774",
      "enter_phone_error": "Please enter your phone number",
      "valid_phone_error": "Please enter a valid phone number",
      //"enter": "Enter",

      //OTP Screen
      "otp_verify": "OTP Verify",
      "verify_your_email": "Verify your\nEmail",
      "verify_your_phone": "Verify your\nPhone number",
      "enter_code_email": "Enter the code from the email we sent\nto ",
      "enter_code_sms": "Enter the code from the SMS we sent\nto ",
      "did_not_receive_code": "Didn't receive any code? ",
      "resend": "RESEND",
      "verify": "Verify",
      "otp_verified_successfully": "OTP Verified Successfully!",


      //"ocr": "OCR",
      "compress_files": "Compress Files",
      //"edit_file": "Edit File",
      //"split_file": "Split File",
      //"rearrange_file": "Rearrange File",
      //"file_transfer": "File Transfer",
      "tool_not_implemented": "Tool {toolName} is not implemented yet",
      "ocr_tool_page": "OCR Tool Page",
      "compress_files_tool_page": "Compress Files Tool Page",
      'norecentdocuments': 'No recent documents found',

    },

    'en_GB': {

      "selected_file": "Selected File",
      "select_format": "Select Format",
      "convert": "Convert",
      "converting": "Converting...",
      "please_select_format_first": "Please select a format first",
      "conversion_failed": "Conversion Failed",
      "ok": "OK",

      "word": "Word",
      "excel": "Excel",
      "powerpoint": "PowerPoint",
      "image": "Image",

      "error_excel_not_implemented": "Excel conversion not implemented",

      "am": "AM",
      "pm": "PM",

      "convert_pdf_format": "Convert PDF Format",
      "convert_pdf_description": "Easily convert PDFs to various formats while retaining their quality, resolution and clarity.",

      "click_to_choose_pdf": "Click to choose PDF file",
      "next": "Next",
      "error_selecting_pdf": "Error selecting PDF",
      "please_select_pdf_first": "Please select a PDF file first",

      "edit": "Edit",
      "failed_to_open_document": "Failed to open document",
      "file_deleted_successfully": "File deleted successfully",
      "generated_document": "Generated Document",

      "original": "Original",
      "cool_tone": "Cool Tone",
      "warm_tone": "Warm Tone",
      "grayscale": "Grayscale",
      "blue_light": "Blue Light",
      "sepia": "Sepia",
      "soft_pastel": "Soft Pastel",

      "crop_document": "Crop Document",
      "done": "Done",
      "cancel": "Cancel",
      "retake": "Retake",
      "filters": "Filters",
      "crop": "Crop",
      "rotate": "Rotate",

      "failed_to_crop_image": "Failed to crop image",
      "failed_to_create_document": "Failed to create document",
      "error_cropping_image": "Error cropping image",
      "error_rotating_image": "Error rotating image",
      "error_applying_filter": "Error applying filter",

      "rearrange_results": "Rearrange Results",
      "processing_document": "Processing document...",
      "reading_pages": "Reading document pages...",
      "rearranging_pdf": "Rearranging PDF pages...",
      "rearranging_docx": "Rearranging document pages...",
      "creating_new_file": "Creating new document...",
      "rearrange_success": "Document successfully rearranged!",
      "error_occurred": "An error occurred",
      "try_again": "Try again",
      "no_app_to_open": "No application found to open this file type",
      "permission_denied": "Permission denied to open the file",
      "file_deleted": "File successfully deleted!",
      "file_renamed": "File successfully renamed!",
      "rearranged_files": "Rearranged files",
      "bytes": "bytes",
      "invalid_page_index": "Invalid page index",
      "no_pages_found": "No pages found in document",
      "empty_file": "Created file is empty",
      "file_not_created": "Output file was not successfully created",
      "file_not_exist": "File does not exist",

      "error_processing_file": "Error processing file",
      "page_number": "Page",
      "selected_file": "Selected file",
      "loading_pdf_previews": "Loading PDF previews...",
      "rearrange": "Rearrange",

      "rearrange_files": "Rearrange Files",
      "rearrange_pages_in_files": "Rearrange Pages in Files",
      "select_file": "Select File",
      "rearrange_file": "Rearrange File",
      "rearrange_file_desc": "Easily drag and reorder PDF pages to organise your document effortlessly.",

      "failed_to_save_file": "Failed to save file",
      "file_renamed_successfully": "File renamed successfully",
      "error_renaming_file": "Error renaming file",
      "no_pages_selected": "No pages selected",
      "no_document_available_to_open": "No document available to open",
      "file_not_found": "File not found",
      "cannot_open_file": "Unable to open the file",
      "zip_file_message": "This is a ZIP file. You may need a ZIP extractor app to view its contents.",
      "error_opening_document": "Error opening document",
      "error_during_deletion": "Error during deletion",
      "processing_generic_document": "Processing document...",
      "error_encountered_fallback": "Error encountered, using fallback method...",
      "creating_pdf_selected_pages": "Creating PDF with selected pages...",
      "pdf_created_successfully": "PDF with selected pages created successfully!",
      "splitting_docx_files": "Splitting DOCX into separate files...",
      "creating_zip_archive": "Creating ZIP archive...",
      "zip_created_successfully": "ZIP archive created successfully!",
      "error_saving_original": "Error occurred. Saving the original file instead...",


      'edit_files': 'Edit Files',
      'edit_files_description': 'Make changes to your images easily. Upload and modify multiple images for a seamless experience.',
      'choose_images': 'Choose Images',
      'click_to_choose_images_from_gallery': 'Click to choose images from gallery',
      'next': 'Next',
      'error_selecting_images': 'Error selecting images',
      'error_capturing_document': 'Error capturing document',
      'error_processing_files': 'Error processing files',
      'please_select_at_least_one_image': 'Please select at least one image',
      'image_removed_successfully': 'Image removed successfully',

      'merged_pdf_file': 'Merge PDF File:',
      'merge_results': 'Merge Results',
      'error_opening_file': 'Error opening file',
      'file_not_found_or_not_processed': 'File not found or not yet processed',
      'merge_completed_successfully': 'PDF files merged successfully!',

      'merge_pdfs': 'Merge PDFs',
      'total_files': 'Total Files',
      'merge_pdf_files': 'Merge PDF Files',
      'merge_file_desc':
      'Effortlessly merge PDF Files for easier sharing, storage, and organization.',
      'select_files': 'Select Files',
      'click_files': 'Click to add PDF files',
      'merge_files': 'Merge Files',
      'please_two_select': 'Please select at least 2 PDF files',
      'selected_files': 'Selected Files',
      'page_order': 'Page order',
      'please_select_pdf_only': 'Please select PDF files only',
      'error_selecting_pdfs': 'Error selecting PDFs',
      'failed_to_merge': 'Failed to merge PDFs',
      'pdf_merger': 'PDF Merger',
      'choose_pdf_files': 'Choose PDF Files',
      'add_more_files': 'Add More Files',
      'remove': 'Remove',
      'reorder': 'Reorder',
      'processing': 'Processing...',
      'merge_complete': 'Merge Complete',
      'file_size': 'File Size',
      'Total_pages': 'Total Pages',
      'drag_to_reorder': 'Drag to reorder',
      'no_files_selected': 'No files selected',
      'maximum_files_limit_reached': 'Maximum files limit reached',
      'file_format_not_supported': 'File format not supported',
      'merge_successful': 'Merge successful',
      'save_merged_file': 'Save merged file',

      'press_again_to_exit': 'Press again to exit',
      // Menu items
      "rename": "Rename",
      "share": "Share",
      "delete": "Delete",

      // Error messages
      "error_sharing_file": "Error sharing file",
      "error_deleting_file": "Error deleting file",

      // Dialog titles and content
      "delete_file": "Delete File",
      "delete_file_confirmation": "Are you sure you want to delete this file?",
      "rename_file": "Rename File",


      // Share content
      "sharing_document_from_ocr_tool": "Sharing document from OCR Tool",
      "document_from_ocr_tool": "Document from OCR Tool",

      // Validation messages
      "please_enter_valid_name": "Please enter a valid name",
      "file_name_already_exists": "File name already exists.",

      "error_creating_zip_file": "Error creating ZIP file",
      "file_saved_successfully": "File saved successfully",
      "failed_to_save_file_generic": "Failed to save file",
      "no_files_to_save": "No files to save",
      "all_files_saved_as_zip": "All files saved as ZIP",
      "compression_summary": "Compression Summary",
      "file_not_compressed_message": "File is not able to compress because it already compressed or not supported.",
      "saving": "Saving...",

      'drag_drop': 'Drag & Drop or click to choose file',
      "compress_file": "Compress File",
      "reduce_file_size": "Reduce File Size",
      "reduce_file_size_description": "Reduce the size of PDFs, documents, and images while preserving original quality.",
      "compression_quality": "Compression Quality",
      "compressing": "Compressing...",
      "compress": "Compress",
      "maximum_compression": "Maximum\nCompression",
      "maximum_quality": "Maximum\nQuality",
      "invalid_file_formats": "Invalid file formats",
      "files_must_be_at_least_mb": "Files must be at least 1 MB",
      "duplicate_files_skipped": "Duplicate files skipped",
      "no_valid_files_selected": "No valid files selected",
      "some_files_were_skipped": "Some files were skipped",
      "duplicates": "duplicate(s)",
      "rejected_too_small": "rejected (too small)",
      "invalid_formats": "invalid format(s)",
      "error_selecting_files": "Error selecting files",
      "please_select_at_least_one_file": "Please select at least one file first",
      "error_compressing_files": "Error compressing files",
      "too_small": "too small",
      "kilobytes": "KB",
      "megabytes": "MB",
      "file_size_format": "{size} {unit}",


      // File Transfer Screen
      'file_transfer': 'File Transfer',
      'easy_transfer_file': 'Easy File Transfer',
      'easy_file_transfer_description': 'Transfer files instantly while keeping quality, resolution, and clarity intact.',
      'choose_file': 'Choose File',
      'extract_text': 'Extract Text',
      'explore_tools': 'Explore Tools',
      'extract_text_from_files': 'Extract Text From Files',
      'extract_text_description': 'Seamlessly extract text copy from multiple images or documents instantly with enhanced accuracy.',

      'select_at_least_one_image': 'Please select at least one image',
      'no_text_in_images': 'No text could be found in the selected images. Try images with clearer text.',
      'error_processing_images': 'Error processing images: @error',
      'image_header': '--- Image @number ---',
      'error_picking_images': 'Error picking images: @error',
      'error_preprocessing_image': 'Error preprocessing image: @error',
      'error_in_ocr': 'Error in OCR: @error',
      'error_deleting_temp_file': 'Error deleting temp file: @error',
      'scan_new': 'Scan New',
      'completed': 'Completed!',
      'please_wait': 'Please wait!',

      'extracted_text_file': 'Extracted Text File:',
      'no_file_available': 'No file available',
      'extracted_text': 'Extracted Text:',
      'error_saving_file': 'Error saving file',
      'could_not_open_file': 'Could not open file',
      'text_copied_to_clipboard': 'Text copied to clipboard',
      'error_copying_text': 'Error copying text',


      'click_to_choose_files': 'Click to choose files',
      'pdf_scanner': 'PDF Scanner',
      'create_your_cv': 'Create Your CV',
      'ocr': 'OCR',
      'merge_file': 'Merge File',
      'edit_file': 'Edit File',
      'split_file': 'Split File',
      'convert_options': 'Convert Options',
      'convert_pdf': 'Convert PDF',
      'convert_image': 'Convert Image',
      'recents': 'Recents',
      'see_all': 'See All',


      'split': 'Split',
      'split_pages': 'Split Pages In File',
      'split_description': 'Effortlessly separate pages from files while keeping everything clear and intact.',
      'split_document': 'Split Document',

      'notifications_alerts': 'Notifications & Alerts',
      'support_feedback': 'Support & Feedback',
      'privacy_policy': 'Privacy Policy',
      'rate_us': 'Rate Us',
      'general': 'General',
      'language': 'Language',
      'confidential_documents': 'Confidential Documents',
      'code_recovery_options': 'Code Recovery Options',
      'email': 'Email',
      'phone_number': 'Phone Number',
      'settings': 'Settings',

      'please_select_one_page': 'Please select at least one page',
      'split_file_progress_screen': 'Split File:',
      'space_saved': 'Space Saved:',
      'total_reduction': 'Total Reductions:',
      'compress_results': 'Compression Results',
      'file_delete': 'File deleted successfully',
      'error_opening_doc': 'Error opening document',
      'drag_and_drop': 'Drag & Drop or click to choose file',
      'select_only_pdf': 'Please select only PDF, DOC or DOCX files',
      'rearrange_file_pages': 'Rearrange Pages In Files',
      'rearrange_file_description': 'Effortlessly drag and reorder PDF pages to organize your document effortlessly.',
      'error': 'Error occurred',
      'processing_doc': 'Processing document...',
      'file_does_not_exist': 'File does not exist',
      'file_empty': 'File is empty',
      'opening_file': 'Opening file:',
      'rearrange_pages': 'Rearrange Pages',
      'selected': 'Selected:',
      'easy_file_transfer': 'Easy Transfer File',

      //Settings Screen Lines
      "notification_enabled": "Notifications enabled successfully",
      "notification_permission": "Notification permission denied",
      "notification_error": "Error enabling notifications",
      "notification_disabled": "Notifications disabled",
      "notification_error_disabled": "Error disabling notifications",
      "notifications_and_alerts": "Notifications & Alerts",
      "support_and_feedback": "Support & Feedback",
      "privacy_and_policy": "Privacy Policy",
      //"rate_us": "Rate Us",
      //"share": "Share",
      //"general": "General",
      //"confidential_document": "Confidential Documents",
      //"code_recovery_options": "Code Recovery Options",
      //"email": "Email",
      //"settings": "Settings",

      //Email Recovery Screen

      "enter_your_email": "Enter your\nEmail",
      "please_enter_your": "Please enter your ",
      "enter": "Enter",
      "email_verify": "Email Verification",
      "enter_email_label": "Enter email*",
      "email_hint": "abc@abc.com",
      "enter_email_error": "Please enter your email",
      "valid_email_error": "Please enter a valid email address",
      'save': 'Save',

      //Phone Recovery Screen
      "phone_verify": "Phone verify",
      "enter_your_phone": "Enter your\nPhone number",
      //"please_enter_your": "Please enter your ",
      //"phone_number": "phone number",
      "enter_mobile_label": "Enter mobile no.*",
      "mobile_hint": "01774",
      "enter_phone_error": "Please enter your phone number",
      "valid_phone_error": "Please enter a valid phone number",
      //"enter": "Enter",

      //OTP Screen
      "otp_verify": "OTP Verification",
      "verify_your_email": "Verify your\nEmail",
      "verify_your_phone": "Verify your\nPhone number",
      "enter_code_email": "Enter the code from the email we sent to",
      "enter_code_sms": "Enter the code from the SMS we sent to",
      "did_not_receive_code": "Didn't receive any code?",
      "resend": "RESEND",
      "verify": "Verify",
      "otp_verified_successfully": "OTP Verified Successfully!",

      //"ocr": "OCR",
      "compress_files": "Compress Files",
      //"edit_file": "Edit File",
      //"split_file": "Split File",
      //"rearrange_file": "Rearrange File",
      //"file_transfer": "File Transfer",
      "tool_not_implemented": "Tool {toolName} is not implemented yet",
      "ocr_tool_page": "OCR Tool Page",
      "compress_files_tool_page": "Compress Files Tool Page",
      'norecentdocuments': 'No recent documents found',

      'file_name': 'File Name',
      'single': 'Single',
      'batch': 'Batch',
      'camera_permission_required': 'Camera permission is required to use the scanner',
      'no_cameras_found': 'No cameras found on device',
      'camera_initialization_failed': 'Camera initialization failed',
      'camera_permission_not_granted': 'Camera permission not granted',
      'grant_camera_permission': 'Grant Camera Permission',
      'initializing_camera': 'Initializing camera...',
      'failed_to_toggle_flash': 'Failed to toggle flash',


    },

    'ur_PK': {

      "selected_file": "منتخب فائل",
      "select_format": "فارمیٹ منتخب کریں",
      "convert": "تبدیل کریں",
      "converting": "تبدیل کیا جا رہا ہے...",
      "please_select_format_first": "براہ مہربانی پہلے ایک فارمیٹ منتخب کریں",
      "conversion_failed": "تبدیل کرنے کا عمل ناکام رہا",
      "ok": "ٹھیک ہے",

      "word": "ورڈ",
      "excel": "ایکسل",
      "powerpoint": "پاورپوائنٹ",
      "image": "تصویر",

      "error_excel_not_implemented": "ایکسل کی تبدیلی کی سہولت دستیاب نہیں",

      "am": "صبح",
      "pm": "شام",

      "convert_pdf": "پی ڈی ایف کو مزید فارمیٹس میں بدلیں",
      "convert_pdf_format": "پی ڈی ایف کی شکل بدلیں",
      "convert_pdf_description": "پی ڈی ایف کی کوالٹی، ریزولوشن اور وضاحت برقرار رکھتے ہوئے مزید فارمیٹس میں آسانی سے بدلیں.",
      "select_file": "فائل منتخب کریں",
      "click_to_choose_pdf": "پی ڈی ایف فائل منتخب کرنے کے لیے کلک کریں",
      "next": "اگلا",
      "please_select_pdf_only": "براہ مہربانی صرف پی ڈی ایف فائل منتخب کریں",
      "error_selecting_pdf": "پی ڈی ایف منتخب کرنے کی صورت میں مسئلہ آیا",
      "please_select_pdf_first": "براہ مہربانی پہلے ایک پی ڈی ایف فائل منتخب کریں",

      "edit": "ترمیم کریں",
      "failed_to_open_document": "دستاویز کھولنے میں ناکام",
      "file_deleted_successfully": "فائل کامیابی کے ساتھ حذف کی گیا!",
      "generated_document": "تخلیق شدہ دستاویز",

      "original": "اصلی",
      "cool_tone": "ٹھنڈی چھایا",
      "warm_tone": "گرم چھایا",
      "grayscale": "سیاہ و سفید",
      "blue_light": "نیلی روشنی",
      "sepia": "سیپیا",
      "soft_pastel": "ہلکے رنگ",

      "crop_document": "دستاویز تراشیں",
      "done": "ہو گیا",
      "cancel": "منسوخ",
      "retake": "دوبارہ لینے کیجیے",
      "filters": "فلٹرز",
      "crop": "تراشیں",
      "rotate": "گھمائیں",

      "failed_to_crop_image": "تصویر تراشنے میں ناکام",
      "failed_to_create_document": "دستاویز کی تخلیق ناکام",
      "error_cropping_image": "تصویر تراشتے وقت مسئلہ",
      "error_rotating_image": "تصویر گھماتے وقت مسئلہ",
      "error_applying_filter": "فلٹر لگانے کی صورت میں مسئلہ",


      "rearrange_results": "نتائج کی ترتیب بدلیں",
      "processing_document": "دستاویز کی پراسیسنگ جاری ہے...",
      "reading_pages": "دستاویز کے صفحات پڑھے جا رہے ہیں...",
      "rearranging_pdf": "پی ڈی ایف صفحات کی ترتیب بدل رہی ہے...",
      "rearranging_docx": "دستاویز صفحات کی ترتیب بدل رہی ہے...",
      "creating_new_file": "نیا دستاویز تیار کیا جا رہا ہے...",
      "rearrange_success": "دستاویز کی ترتیب کامیاب ہوگئی!",
      "error_occurred": "خرابی پیش آئی",
      "try_again": "دوبارہ کوشش کریں",
      "file_opened": "فائل کھول دی گئی!",
      "no_app_to_open": "اس فائل کی قسم کھولنے کے لیے کوئی ایپلیکیشن نہیں ملی",
      "permission_denied": "فائل کھولنے کی اجازت نہیں ہے",
      "file_deleted": "فائل کو کامیابی کے ساتھ حذف کر दिया گیا!",
      "file_renamed": "فائل کا نام کامیابی کے ساتھ بدل दिया گیا!",
      "rearranged_files": "دوبارہ ترتیب دی گئیں فائلیں",
      "bytes": "بائٹس",
      "invalid_page_index": "غلط صفحہ نمبر",
      "no_pages_found": "دستاویز میں کوئی صفحات نہیں ملے",
      "empty_file": "نئی فائل خالی ہے",
      "file_not_created": "آؤٹ پٹ فائل تیار نہیں کی جا سکی",
      "file_not_exist": "فائل موجود نہیں ہے",

      "error_processing_file": "فائل پر کارروائی میں خرابی",
      "page_number": "صفحہ",
      "selected_file": "منتخب فائل",
      "loading_pdf_previews": "PDF پیش نظارے لوڈ ہو رہے ہیں",
      "rearrange": "دوبارہ ترتیب دیں",

      "rearrange_files": "فائلوں کو دوبارہ ترتیب دیں",
      "rearrange_pages_in_files": "فائلوں میں صفحات کو دوبارہ ترتیب دیں",
      "select_file": "فائل منتخب کریں",
      "rearrange_file": "فائل کو دوبارہ ترتیب دیں",
      "rearrange_file_desc": "آسانی سے PDF صفحات کو کھینچیں اور دوبارہ ترتیب دیں تاکہ آپ کا دستاویز بآسانی منظم ہو جائے۔",

      "failed_to_save_file": "فائل محفوظ کرنے کی کوشش ناکام ہوگئی",
      "file_renamed_successfully": "فائل کا نام کامیابی کے ساتھ بدل दिया گیا",
      "error_renaming_file": "فائل کا نام بدلنے کے دوران مسئلہ پیش آیا",
      "no_pages_selected": "کوئی صفحات منتخب نہیں ہیں",
      "no_document_available_to_open": "کھولنے کے لیے کوئی مزید دستاویز دستیاب نہیں",
      "file_not_found": "فائل نہیں ملی",
      "cannot_open_file": "فائل کھولی نہیں جا سکتی",
      "zip_file_message": "یہ ایک ZIP فائل ہے. مواد دیکھنے کے لیے ZIP ایکسٹریکٹر کی ضرورت ہے.",
      "error_opening_document": "دستاویز کھولنے کی کوشش کے دوران مسئلہ پیش آیا",
      "error_during_deletion": "فائل کو حذف کرنے کے دوران مسئلہ پیش آیا",
      "processing_generic_document": "دستاویز کی تیاری جاری ہے...",
      "error_encountered_fallback": "خرابی آگئی، بیک اپ طریقہ استعمال کیا جا رہا ہے...",
      "creating_pdf_selected_pages": "منتخب صفحات کی PDF تیار کی جا رہی ہے...",
      "pdf_created_successfully": "منتخب صفحات کی PDF کامیابی کے ساتھ تیار کی گی!",
      "splitting_docx_files": "DOCX فائلیں علیحدہ کی جا رہی ہیں...",
      "creating_zip_archive": "ZIP فائل تیار کی جا رہی ہے...",
      "zip_created_successfully": "ZIP فائل کامیابی کے ساتھ تیار کی گی!",
      "error_saving_original": "خرابی آگئی. اصل فائل کو محفوظ کیا جا رہا ہے...",


      "edit_files": "فائلیں ترمیم کریں",
      "edit_files_description": "آسانی کے ساتھ اپنی تصاویر کی ترمیم کریں۔ مزید سہولت کے لیے ایک ساتھ متعدد تصاویر اپلوڈ اور ترمیم کریں۔",
      "choose_images": "تصاویر منتخب کریں",
      "click_to_choose_images_from_gallery": "گیلری سے تصاویر منتخب کرنے کے لیے کلک کریں",
      "next": "اگلا",
      "error_selecting_images": "تصاویر منتخب کرنے کے دوران مسئلہ پیش آیا",
      "error_capturing_document": "دستاویز کیپچر کرنے کے دوران مسئلہ پیش آیا",
      "error_processing_files": "فائلیں پراسیس کرنے کے دوران مسئلہ پیش آیا",
      "please_select_at_least_one_image": "براہ مہربانی کم از کم ایک تصویر منتخب کریں",
      "image_removed_successfully": "تصویر کامیابی کے ساتھ ہٹا دی گیئ",

      "merged_pdf_file": "PDF فائل کو مرج کریں:",
      "merge_results": "مرج کے نتائج",
      "error_opening_file": "فائل کھولنے کے دوران مسئلہ پیش آیا",
      "file_not_found_or_not_processed": "فائل نہیں ملی یا ابھی تک پراسیس نہیں کی گی",
      "merge_completed_successfully": "PDF فائلیں کامیابی کے ساتھ مرج کی گئیں!",


      "total_files": "کل فائلیں",
      'merge_pdfs': 'پی ڈی ایف ضم کریں',
      'merge_pdf_files': 'پی ڈی ایف فائلز ضم کریں',
      'merge_file_desc':
      'آسانی سے شیئرنگ، اسٹوریج اور تنظیم کے لیے پی ڈی ایف فائلز کو بآسانی ضم کریں۔',
      'select_files': 'فائلز منتخب کریں',
      'click_files': 'پی ڈی ایف فائلز شامل کرنے کے لیے کلک کریں',
      'merge_files': 'فائلز ضم کریں',
      'please_two_select': 'براہ کرم کم از کم 2 پی ڈی ایف فائلز منتخب کریں',
      'selected_files': 'منتخب شدہ فائلز',
      'page_order': 'صفحے کی ترتیب',
      'please_select_pdf_only': 'براہ کرم صرف پی ڈی ایف فائلز منتخب کریں',
      'error_selecting_pdfs': 'پی ڈی ایف منتخب کرنے میں خرابی',
      'failed_to_merge': 'پی ڈی ایف ضم کرنے میں ناکام',
      'pdf_merger': 'پی ڈی ایف ضم کرنے والا',
      'choose_pdf_files': 'پی ڈی ایف فائلز منتخب کریں',
      'add_more_files': 'مزید فائلز شامل کریں',
      'remove': 'ہٹائیں',
      'reorder': 'دوبارہ ترتیب دیں',
      'processing': 'پروسیسنگ...',
      'merge_complete': 'ضم مکمل',
      'file_size': 'فائل کا سائز',
      'total_pages': 'کل صفحات',
      'drag_to_reorder': 'دوبارہ ترتیب دینے کے لیے کھینچیں',
      'no_files_selected': 'کوئی فائل منتخب نہیں',
      'maximum_files_limit_reached': 'زیادہ سے زیادہ فائلز کی حد پہنچ گئی',
      'file_format_not_supported': 'فائل فارمیٹ سپورٹ نہیں',
      'merge_successful': 'ضم کامیاب',
      'save_merged_file': 'ضم شدہ فائل محفوظ کریں',

      'press_again_to_exit': 'خروج کے لیے دوبارہ دبائیں',
      // Menu items
      "rename": "نام بدلیں",
      "share": "شیئر کریں",
      "delete": "حذف کریں",

      // Error messages
      "error_sharing_file": "فائل کا اشتراک کرنے کے دوران مسئلہ پیش آیا",
      "error_deleting_file": "فائل کو حذف کرنے کے دوران مسئلہ پیش آیا",

      // Dialog titles and content
      "delete_file": "فائل کو حذف کریں",
      "delete_file_confirmation": " کیا آپ واقعی اس فائل کو حذف کرنا چاہتے ہیں؟",
      "rename_file": "فائل کا نام بدلیں",

      // Share content
      "sharing_document_from_ocr_tool": "متن کی شراکت کی جا رہی ہے بذریعہ OCR ٹول",
      "document_from_ocr_tool": "OCR ٹول کی جانب سے दस्तاویز",

      // Validation messages
      "please_enter_valid_name": "براہ مہربانی ایک صحیح نام درج کریں",
      "file_name_already_exists": "فائل کا نام پہلے سے موجود ہے",


      "error_creating_zip_file": "ZIP فائل کی تخلیق کے دوران مسئلہ پیش آیا",
      "file_saved_successfully": "فائل کو کامیابی کے ساتھ محفوظ کر لیا گیا",
      "failed_to_save_file_generic": "فائل کو محفوظ کرنے کی ناکامی",
      "no_files_to_save": "محفوظ کرنے کے لیے کوئی فائلیں نہیں ہیں",
      "all_files_saved_as_zip": "تمام فائلیں ZIP کی صورت میں محفوظ کی گئیں",
      "compression_summary": "کمپریشن کا خلاصہ",
      "file_not_compressed_message": "فائل کو کمپریس نہیں کیا جا سکا کیونکہ وہ پہلے سے ہی کمپریس کی جا چکی ہے یا معاونت نہیں کی جاتی.",
      "save": "محفوظ کریں",
      "saving": "محفوظ کیا جا رہا ہے...",


      "drag_drop": "فائل کو ڈریگ اینڈ ڈراپ کریں یا منتخب کرنے کے لیے کلک کریں",
      "compress_file": "فائل کمپریس کریں",
      "reduce_file_size": "فائل کا سائز کم کریں",
      "reduce_file_size_description": "پی ڈی ایف، دستاویزات اور تصاویر کا سائزکم کریں بغیر معیار کھوئے.",
      "compression_quality": "کمپریشن کوالٹی",
      "compressing": "کمپریس ہو رہا ہے...",
      "compress": "کمپریس کریں",
      "maximum_compression": "زیادہ سے زیادہ\nکمپریشن",
      "maximum_quality": "زیادہ سے زیادہ\nکوالٹی",
      "invalid_file_formats": "غلط فائل فارمیٹس",
      "files_must_be_at_least_mb": "فائلوں کا سائز کم از کم 1 MB ہونا چاہیے",
      "duplicate_files_skipped": "ڈپلیکیٹ فائلز چھوڑ دی گئیں",
      "no_valid_files_selected": "کوئی درست فائل منتخب نہیں کی گئی",
      "some_files_were_skipped": "کچھ فائلز چھوڑ دی گئیں",
      "duplicates": "ڈپلیکیٹ",
      "rejected_too_small": "مسترد (بہت چھوٹی)",
      "invalid_formats": "غلط فارمیٹس",
      "error_selecting_files": "فائلز منتخب کرنے میں خرابی",
      "please_select_at_least_one_file": "پہلے کم از کم ایک فائل منتخب کریں",
      "error_compressing_files": "فائلز کمپریس کرنے میں خرابی",
      "too_small": "بہت چھوٹی",
      "kilobytes": "کے بی",
      "megabytes": "ایم بی",
      "file_size_format": "{size} {unit}",



      // File Transfer Screen
      'file_transfer': 'فائل ٹرانسفر',
      'easy_transfer_file': 'آسان فائل ٹرانسفر',
      'easy_file_transfer_description': 'فائلوں کو فوری طور پر منتقل کریں جبکہ معیار، ریزولوشن اور وضاحت برقرار رکھیں۔',
      'choose_file': 'فائل منتخب کریں',
      'extract_text': 'ٹیکسٹ نکالیں',
      'explore_tools': 'اوزار دریافت کریں',
      'extract_text_from_files': 'فائلوں سے متن نکالیں',
      'extract_text_description': ' ایک ساتھ متعدد تصاویر یا فائلوں سے مزید صحیح طریقے کے ساتھ متن نکالیں',


      'file_name': 'فائل کا نام',
      'single': 'واحد',
      'batch': 'بیچ',
      'camera_permission_required': 'اسکینر استعمال کرنے کے لیے کیمرے کی اجازت درکار ہے',
      'no_cameras_found': 'آلے پر کوئی کیمرا نہیں ملا',
      'camera_initialization_failed': 'کیمرا شروع کرنے میں ناکامی',
      'camera_permission_not_granted': 'کیمرے کی اجازت نہیں دی گئی',
      'grant_camera_permission': 'کیمرے کی اجازت دیں',
      'initializing_camera': 'کیمرا شروع کر رہے ہیں...',
      'failed_to_toggle_flash': 'فلیش آن/آف کرنے میں ناکامی',


      'completed': 'مکمل!',
      'please_wait': 'براہ کرم انتظار کریں!',
      'click_to_choose_files': 'فائلیں منتخب کرنے کے لیے کلک کریں',
      'scan_new': 'نیا سکین کریں',
      'extracted_text_file': 'نکالا گیا متن فائل:',
      'no_file_available': 'کوئی فائل دستیاب نہیں',
      'extracted_text': 'نکالا گیا متن:',
      'error_saving_file': 'فائل محفوظ کرنے میں خرابی',
      'could_not_open_file': 'فائل کھولا نہیں جا سکا',
      'text_copied_to_clipboard': 'متن کلپ بورڈ میں کاپی ہو گیا',
      'error_copying_text': 'متن کاپی کرنے میں خرابی',


      'pdf_scanner': 'پی ڈی ایف اسکینر',
      'create_your_cv': 'اپنا سی وی بنائیں',
      'ocr': 'او سی آر',
      'merge_file': 'فائلیں ضم کریں',
      'edit_file': 'فائل میں ترمیم کریں',
      'split_file': 'فائل کو تقسیم کریں',
      'convert_options': 'تبدیلی کے اختیارات',
      'convert_pdf': 'پی ڈی ایف تبدیل کریں',
      'convert_image': 'تصویر تبدیل کریں',
      'recents': 'حالیہ',
      'see_all': 'سب دیکھیں',

      'select_at_least_one_image': 'براہ مہربانی کم از کم ایک تصویر منتخب کریں',
      'no_text_in_images': 'منتخب تصاویر میں کوئی متن نہیں ملا۔ مزید واضح تصاویر کی کوشش کریں',
      'error_processing_images': 'تصاویر کی پراسیسنگ میں مسئلہ: @error',
      'image_header': '--- تصویر @number ---',
      'error_picking_images': 'تصاویر منتخب کرنے کی صورت میں مسئلہ: @error',
      'error_preprocessing_image': 'تصویر کی پیش پراسیسنگ میں مسئلہ: @error',
      'error_in_ocr': 'OCR کی صورت میں مسئلہ: @error',
      'error_deleting_temp_file': 'عارضی فائل کو حذف کرنے کی صورت میں مسئلہ: @error',


      'split': 'تقسیم کریں',
      'split_pages': 'فائل میں صفحات تقسیم کریں',
      'split_description': 'صفحات کو فائلوں سے آسانی سے الگ کریں جبکہ سب کچھ واضح اور برقرار رکھیں۔',
      'split_document': 'دستاویز تقسیم کریں',

      'notifications_alerts': 'اطلاعات اور انتباہات',
      'support_feedback': 'سپورٹ اور فیڈبک',
      'privacy_policy': 'پرائیویسی پالیسی',
      'rate_us': 'ہمیں ریٹ کریں',
      'general': 'عمومی',
      'language': 'زبان',
      'confidential_documents': 'خفیہ دستاویزات',
      'code_recovery_options': 'کوڈ بحالی کے اختیارات',
      'email': 'ای میل',
      'phone_number': 'فون نمبر',
      'settings': 'سیٹنگز',

      'please_select_one_page': 'براہ کرم کم از کم ایک صفحہ منتخب کریں',
      'split_file_progress_screen': 'فائل تقسیم کریں:',
      'compressed': 'کمپریس شدہ فائلیں:',
      'space_saved': 'محفوظ شدہ جگہ:',
      'total_reduction': 'کل کمی:',
      'compress_results': 'کمپریشن کے نتائج',
      'file_delete': 'فائل کامیابی سے حذف ہو گئی',
      'error_opening_doc': 'دستاویز کھولنے میں خرابی',
      'drag_and_drop': 'فائل منتخب کرنے کے لیے ڈریگ کریں یا کلک کریں',
      'select_only_pdf': 'براہ کرم صرف PDF، DOC یا DOCX فائلیں منتخب کریں',
      'rearrange_file_pages': 'فائل کے صفحات دوبارہ ترتیب دیں',
      'rearrange_file_description': 'پی ڈی ایف کے صفحات کو آسانی سے گھسیٹیں اور دوبارہ ترتیب دیں تاکہ آپ کی دستاویز منظم ہو جائے۔',

      'error': 'خرابی پیش آگئی',
      'processing_doc': 'دستاویز پر کارروائی ہو رہی ہے...',
      'file_does_not_exist': 'فائل موجود نہیں',
      'file_empty': 'فائل خالی ہے',
      'opening_file': 'فائل کھولی جا رہی ہے:',
      'rearrange_pages': 'صفحات کی ترتیب تبدیل کریں',
      'selected': 'منتخب شدہ:',
      'easy_file_transfer': 'آسان فائل ٹرانسفر',

      //Settings Screen Lines
      "notification_enabled": "اطلاعات کامیابی سے فعال ہو گئیں",
      "notification_permission": "اطلاعات کی اجازت مسترد کر دی گئی",
      "notification_error": "اطلاعات کو فعال کرتے وقت خرابی",
      "notification_disabled": "اطلاعات غیر فعال کر دی گئی ہیں",
      "notification_error_disabled": "اطلاعات کو غیر فعال کرتے وقت خرابی",
      "notifications_and_alerts": "اطلاعات اور الرٹس",
      "support_and_feedback": "مدد اور آراء",
      "privacy_and_policy": "رازداری کی پالیسی",
      //"rate_us": "ہمیں ریٹنگ دیں",
      //"share": "شیئر کریں",
      //"general": "عمومی",
      "confidential_document": "خفیہ دستاویزات",
      //"code_recovery_options": "کوڈ بازیابی کے اختیارات",
      //"email": "ای میل",
      //"settings": "ترتیبات",

      // Email Recovery Screen
      "enter_your_email": "اپنی\nای میل درج کریں",
      "please_enter_your": " براہ کرم اپنی",
      "enter": "درج کریں",
      "email_verify": "ای میل کی تصدیق",
      "enter_email_label": "ای میل درج کریں*",
      "email_hint": "abc@abc.com",
      "enter_email_error": "براہ کرم اپنی ای میل درج کریں",
      "valid_email_error": "براہ کرم درست ای میل پتہ درج کریں",

      //Phone Recovery Screen
      "phone_verify": "فون کی تصدیق",
      "enter_your_phone": "اپنا\nفون نمبر درج کریں",
      //"please_enter_your": "براہ کرم اپنا ",
      //"phone_number": "فون نمبر",
      "enter_mobile_label": "موبائل نمبر درج کریں*",
      "mobile_hint": "01774",
      "enter_phone_error": "براہ کرم اپنا فون نمبر درج کریں",
      "valid_phone_error": "براہ کرم درست فون نمبر درج کریں",

      //OTP Screen
      "otp_verify": "او ٹی پی کی تصدیق",
      "verify_your_email": "اپنی\nای میل کی تصدیق کریں",
      "verify_your_phone": "اپنے\nفون نمبر کی تصدیق کریں",
      "enter_code_email": "ہم نے جو ای میل بھیجی ہے اس کا کوڈ درج کریں",
      "enter_code_sms": "ہم نے جو ایس ایم ایس بھیجا ہے اس کا کوڈ درج کریں",
      "did_not_receive_code": "کوئی کوڈ موصول نہیں ہوا؟",
      "resend": "دوبارہ بھیجیں",
      "verify": "تصدیق کریں",
      "otp_verified_successfully": "او ٹی پی کی کامیاب تصدیق ہو گئی!",

      "compress_files": "فائلز کمپریس کریں",
      "tool_not_implemented": "ٹول {toolName} ابھی تیار نہیں ہے",
      "ocr_tool_page": "او سی آر ٹول صفحہ",
      "compress_files_tool_page": "فائلز کمپریس کرنے کا ٹول صفحہ",
      'norecentdocuments': 'حالیہ فائلیں نہیں ملیں',


    },

    'zh_CN': {

      "selected_file": "已选择文件",
      "select_format": "选择格式",
      "convert": "转换",
      "converting": "正在转换...",
      "please_select_format_first": "请先选择格式",
      "conversion_failed": "转换失败",
      "ok": "确定",

      "word": "Word",
      "excel": "Excel",
      "powerpoint": "PowerPoint",
      "image": "图片",

      "error_excel_not_implemented": "未实现 Excel 转换",

      "am": "上午",
      "pm": "下午",

      "convert_pdf": "转换 PDF",
      "convert_pdf_format": "转换 PDF 格式",
      "convert_pdf_description": "轻松地将 PDF 转换为不同格式，同时保持其质量、分辨率和清晰度。",
      "select_file": "选择文件",
      "click_to_choose_pdf": "点击选择 PDF 文件",
      "next": "下一步",
      "please_select_pdf_only": "请输入仅选择 PDF 文件",
      "error_selecting_pdf": "选择 PDF 文件时发生错误",
      "please_select_pdf_first": "请先选择 PDF 文件",

      "edit": "编辑",
      "failed_to_open_document": "打开文件失败",
      "file_deleted_successfully": "文件已成功删除",
      "generated_document": "已生成文件",

      "original": "原图",
      "cool_tone": "冷色调",
      "warm_tone": "暖色调",
      "grayscale": "灰度",
      "blue_light": "蓝光",
      "sepia": "棕褐色",
      "soft_pastel": "柔和粉彩",

      "crop_document": "裁剪文件",
      "done": "完成",
      "cancel": "取消",
      "retake": "重新拍摄",
      "filters": "滤镜",
      "crop": "裁剪",
      "rotate": "旋转",

      "failed_to_crop_image": "裁剪图片失败",
      "failed_to_create_document": "创建文件失败",
      "error_cropping_image": "裁剪图片时发生错误",
      "error_rotating_image": "旋转图片时发生错误",
      "error_applying_filter": "应用滤镜时发生错误",

      "rearrange_results": "重新安排结果",
      "processing_document": "正在处理文档...",
      "reading_pages": "正在阅读文档页面...",
      "rearranging_pdf": "正在重新安排 PDF 页...",
      "rearranging_docx": "正在重新安排 Word 文档页面...",
      "creating_new_file": "正在创建新文档...",
      "rearrange_success": "文档重新安排成功!",
      "error_occurred": "发生错误",
      "try_again": "再试一次",
      "save": "保存",
      "saving": "保存中...",
      "file_opened": "文件已成功打开!",
      "no_app_to_open": "未找到可以打开此文件类型的应用程序",
      "permission_denied": "无权打开此文件",
      "file_deleted": "文件已成功删除!",
      "file_renamed": "文件已重命名!",
      "rearranged_files": "已重新安排的文件",
      "bytes": "字节数",
      "invalid_page_index": "无效页面序列",
      "no_pages_found": "未找到页面",
      "empty_file": "创建出的文件是空的",
      "file_not_created": "未能成功创建输出文件",
      "file_not_exist": "文件不存在",

      "error_processing_file": "文件处理错误",
      "page_number": "第",
      "selected_file": "已选择文件",
      "loading_pdf_previews": "正在加载PDF预览",
      "rearrange": "重新排列",


      "rearrange_files": "重新排列文件",
      "rearrange_pages_in_files": "重新排列文件中的页面",
      "select_file": "选择文件",
      "rearrange_file": "重新排列文件",
      "rearrange_file_desc": "轻松拖放和重新排序PDF页面，毫不费力地整理您的文档。",

      "failed_to_save_file": "保存文件失败",
      "file_renamed_successfully": "文件重命名成功",
      "error_renaming_file": "重命名文件时发生错误",
      "no_pages_selected": "未选择页面",
      "no_document_available_to_open": "无法打开文档",
      "file_not_found": "未找到文件",
      "cannot_open_file": "无法打开文件",
      "zip_file_message": "这是一个ZIP文件，需要ZIP解压器查看其中的内容。",
      "error_opening_document": "打开文档时发生错误",
      "error_during_deletion": "删除时发生错误",
      "processing_generic_document": "正在处理文档...",
      "error_encountered_fallback": "发生错误，正在使用备用方案...",
      "creating_pdf_selected_pages": "正在根据所选页面创建PDF...",
      "pdf_created_successfully": " PDF已根据所选页面成功创建!",
      "splitting_docx_files": "正在将DOCX文件拆分为独立文件...",
      "creating_zip_archive": "正在创建ZIP压缩文件...",
      "zip_created_successfully": "ZIP压缩文件已成功创建!",
      "error_saving_original": "发生错误。正在保存原文件...",

      "edit_files": "编辑文件",
      "edit_files_description": "轻松修改您的图片。上传并修改多张图片以获得无缝体验。",
      "choose_images": "选择图片",
      "click_to_choose_images_from_gallery": "点击从图库中选择图片",
      "next": "下一步",
      "error_selecting_images": "选择图片时发生错误",
      "error_capturing_document": "捕捉文档时发生错误",
      "error_processing_files": "处理文件时发生错误",
      "please_select_at_least_one_image": "请输入至少一张图片",
      "image_removed_successfully": "图片已成功移除",

      "merged_pdf_file": "合并 PDF 文件：",
      "merge_results": "合并结果",
      "error_opening_file": "打开文件时发生错误",
      "file_not_found_or_not_processed": "未找到文件或尚未处理",
      "merge_completed_successfully": "PDF 文件已成功合并!",

      'merge': '合并',
      "total_files": "文件总数",
      'merge_pdfs': '合并PDF',
      'merge_pdf_files': '合并PDF文件',
      'merge_file_desc':
      '轻松合并PDF文件，便于共享、存储和整理。',
      'select_files': '选择文件',
      'click_files': '点击添加PDF文件',
      'merge_files': '合并文件',
      'please_two_select': '请至少选择2个PDF文件',
      'selected_files': '已选择的文件',
      'page_order': '页面顺序',
      'please_select_pdf_only': '请只选择PDF文件',
      'error_selecting_pdfs': '选择PDF文件时出错',
      'failed_to_merge': '合并PDF失败',
      'pdf_merger': 'PDF合并器',
      'choose_pdf_files': '选择PDF文件',
      'add_more_files': '添加更多文件',
      'remove': '移除',
      'reorder': '重新排序',
      'processing': '处理中...',
      'merge_complete': '合并完成',
      'file_size': '文件大小',
      'total_pages': '总页数',
      'drag_to_reorder': '拖拽重新排序',
      'no_files_selected': '未选择文件',
      'maximum_files_limit_reached': '已达到最大文件数限制',
      'file_format_not_supported': '不支持的文件格式',
      'merge_successful': '合并成功',
      'save_merged_file': '保存合并文件',

      "press_again_to_exit": "再按以退出",


      // Menu items
      "rename": "重命名",
      "share": "共享",
      "delete": "删除",

      // Error messages
      "error_sharing_file": "共享文件时发生错误",
      "error_deleting_file": "删除文件时发生错误",

      // Dialog titles and content
      "delete_file": "删除文件",
      "delete_file_confirmation": "你确定要删除这个文件吗？",
      "rename_file": "重命名文件",

      // Success messages

      // Share content
      "sharing_document_from_ocr_tool": "从 OCR 工具共享文档",
      "document_from_ocr_tool": "OCR 工具中的文档",

      // Validation messages
      "please_enter_valid_name": "请输入一个有效的名称",
      "file_name_already_exists": "文件名已存在",

      "drag_drop": "拖放文件或点击以选择文件",

      "compress_file": "压缩文件",
      "reduce_file_size": "减少文件大小",
      "reduce_file_size_description": "减少 PDF、文档和图片的大小，同时保持原有质量。",
      "compression_quality": "压缩质量",
      "compressing": "正在压缩...",
      "compress": "压缩",
      "maximum_compression": "最大\n压缩",
      "maximum_quality": "最高\n质量",
      "invalid_file_formats": "无效的文件格式",
      "files_must_be_at_least_mb": "文件大小必须至少为1MB",
      "duplicate_files_skipped": "跳过重复文件",
      "no_valid_files_selected": "未选择有效文件",
      "some_files_were_skipped": "某些文件被跳过",
      "duplicates": "重复文件",
      "rejected_too_small": "已拒绝（太小）",
      "invalid_formats": "无效格式",
      "error_selecting_files": "选择文件时出错",
      "please_select_at_least_one_file": "请先选择至少一个文件",
      "error_compressing_files": "压缩文件时出错",
      "too_small": "太小",
      "kilobytes": "KB",
      "megabytes": "MB",
      "file_size_format": "{size} {unit}",

      "error_creating_zip_file": "创建 ZIP 文件时发生错误",
      "file_saved_successfully": "文件保存成功",
      "failed_to_save_file_generic": "保存文件失败",
      "no_files_to_save": "无需保存的文件",
      "all_files_saved_as_zip": "所有文件均已保存为 ZIP 文件",
      "compression_summary": "压缩摘要",
      "file_not_compressed_message": "文件无法压缩，因为它已被压缩或不受支持。",



      // File Transfer Screen
      'file_transfer': '文件传输',
      'easy_transfer_file': '简易文件传输',
      'easy_file_transfer_description': '即时传输文件，同时保持质量、分辨率和清晰度。',
      'choose_file': '选择文件',
      'extract_text': '提取文本',
      'explore_tools': '探索工具',
      'extract_text_from_files': '从文件中提取文字',
      'extract_text_description': '无障碍地从多个图片或文件中立即且高度准确地提取文字。',
      'click_to_choose_files': '单击以选择文件',
      'scan_new': '扫描新版',
      'completed': '完成！',
      'please_wait': '请稍等！',

      'file_name': '文件名',
      'single': '单个',
      'batch': '批量',
      'camera_permission_required': '使用扫描仪需要相机权限',
      'no_cameras_found': '设备上未找到相机',
      'camera_initialization_failed': '相机初始化失败',
      'camera_permission_not_granted': '相机权限未授权',
      'grant_camera_permission': '授予相机权限',
      'initializing_camera': '正在初始化相机...',
      'failed_to_toggle_flash': '切换闪光灯失败',


      'select_at_least_one_image': '请输入至少选择一张图片',
      'no_text_in_images': '所选图片中未找到文字。请试用文字更清晰的图片。',
      'error_processing_images': '处理图片时出错：@error',
      'image_header': '---图片 @number ---',
      'error_picking_images': '选择图片时出错：@error',
      'error_preprocessing_image': '预处理图片时出错：@error',
      'error_in_ocr': 'OCR时发生错误：@error',
      'error_deleting_temp_file': '删除临时文件时出错：@error',

      'extracted_text_file': '提取的文本文件：',
      'no_file_available': '没有可用文件',
      'extracted_text': '提取的文本：',
      'error_saving_file': '保存文件时出错',
      'could_not_open_file': '无法打开文件',
      'text_copied_to_clipboard': '文本已复制到剪贴板',
      'error_copying_text': '复制文本时出错',




      'pdf_scanner': 'PDF扫描仪',
      'create_your_cv': '创建您的简历',
      'ocr': '光学字符识别',
      'merge_file': '合并文件',
      'edit_file': '编辑文件',
      'split_file': '拆分文件',
      'convert_options': '转换选项',
      'convert_pdf': '转换PDF',
      'convert_image': '转换图像',
      'recents': '最近使用',
      'see_all': '查看全部',

      'split': '拆分',
      'split_pages': '拆分文件中的页面',
      'split_description': '轻松从文件中分离页面，同时保持内容清晰完整。',
      'split_document': '拆分文档',

      'notifications_alerts': '通知和提醒',
      'support_feedback': '支持与反馈',
      'privacy_policy': '隐私政策',
      'rate_us': '给我们评分',
      'general': '通用',
      'language': '语言',
      'confidential_documents': '机密文件',
      'code_recovery_options': '代码恢复选项',
      'email': '电子邮件',
      'phone_number': '电话号码',
      'settings': '设置',

      'please_select_one_page': '请至少选择一页',
      'split_file_progress_screen': '拆分文件：',
      'compressed': '已压缩的文件：',
      'space_saved': '节省空间：',
      'total_reduction': '总减少量：',
      'compress_results': '压缩结果',
      'file_delete': '文件已成功删除',
      'error_opening_doc': '打开文档出错',
      'drag_and_drop': '拖放或点击以选择文件',
      'select_only_pdf': '请选择 PDF、DOC 或 DOCX 文件',
      'rearrange_file_pages': '重新排列文件页面',
      'rearrange_file_description': '轻松拖动和重新排列PDF页面，轻松组织文档。',
      'error': '发生错误',
      'processing_doc': '正在处理文档...',
      'file_does_not_exist': '文件不存在',
      'file_empty': '文件为空',
      'opening_file': '正在打开文件：',
      'rearrange_pages': '重新排列页面',
      'selected': '已选择：',
      'easy_file_transfer': '轻松文件传输',

      //Settings Screen Lines
      "notification_enabled": "通知已成功启用",
      "notification_permission": "通知权限被拒绝",
      "notification_error": "启用通知时出错",
      "notification_disabled": "通知已禁用",
      "notification_error_disabled": "禁用通知时出错",
      "notifications_and_alerts": "通知和提醒",
      "support_and_feedback": "支持与反馈",
      "privacy_and_policy": "隐私政策",
      "confidential_document": "机密文件",


      //Email Recovery Screen
      "enter_your_email": "请输入您的\n电子邮件",
      "please_enter_your": "请输入您的 ",
      "enter": "输入",
      "email_verify": "电子邮件验证",
      "enter_email_label": "输入电子邮件*",
      "email_hint": "abc@abc.com",
      "enter_email_error": "请输入您的电子邮件",
      "valid_email_error": "请输入有效的电子邮件地址",

      //Phone Recovery Screen
      "phone_verify": "手机验证",
      "enter_your_phone": "请输入您的\n手机号码",
      "enter_mobile_label": "输入手机号码*",
      "mobile_hint": "01774",
      "enter_phone_error": "请输入您的手机号码",
      "valid_phone_error": "请输入有效的手机号码",

      //OTP Screen
      "otp_verify": "验证码验证",
      "verify_your_email": "验证您的\n邮箱",
      "verify_your_phone": "验证您的\n手机号",
      "enter_code_email": "请输入我们发送到您的邮箱的验证码",
      "enter_code_sms": "请输入我们发送到您手机的验证码",
      "did_not_receive_code": "未收到验证码？",
      "resend": "重新发送",
      "verify": "验证",
      "otp_verified_successfully": "验证码验证成功！",

      "compress_files": "压缩文件",
      "tool_not_implemented": "工具 {toolName} 尚未实现",
      "ocr_tool_page": "光学字符识别工具页面",
      "compress_files_tool_page": "压缩文件工具页面",
      'norecentdocuments': '未找到最近的文件',

    },

    'de_DE': {

      "selected_file": "Ausgewählte Datei",
      "select_format": "Format auswählen",
      "convert": "Konvertieren",
      "converting": "Konvertiert...",
      "please_select_format_first": "Bitte zuerst das Format auswählen",
      "conversion_failed": "Konvertierung ist fehlgeschlagen",
      "ok": "OK",

      "word": "Word",
      "excel": "Excel",
      "powerpoint": "PowerPoint",
      "image": "Bild",

      "error_excel_not_implemented": "Die Konvertierung in Excel ist nicht implementiert",

      "am": "Vormittag",
      "pm": "Nachmittag",

      "convert_pdf": "PDF konvertieren",
      "convert_pdf_format": "PDF-Format konvertieren",
      "convert_pdf_description": "Konvertieren Sie PDFs problemlos in verschiedene Formate, wobei Qualität, Auflösung und Klarheit erhalten bleiben.",
      "select_file": "Datei auswählen",
      "click_to_choose_pdf": "Zum Auswählen einer PDF klicken",
      "next": "Weiter",
      "please_select_pdf_only": "Bitte wählen Sie nur PDF Dateien aus",
      "error_selecting_pdf": "Fehler beim Auswählen der PDF",
      "please_select_pdf_first": "Bitte wählen Sie zuerst eine PDF aus",

      "edit": "Bearbeiten",
      "failed_to_open_document": "Dokument konnte nicht geöffnet werden",
      "file_deleted_successfully": "Datei wurde erfolgreich gelöscht",
      "generated_document": "Generiertes Dokument",

      "original": "Original",
      "cool_tone": "Kühler Ton",
      "warm_tone": "Warmer Ton",
      "grayscale": "Graustufe",
      "blue_light": "Blaulicht",
      "sepia": "Sepia",
      "soft_pastel": "Weiches Pastell",

      "crop_document": "Dokument zuschneiden",
      "done": "Fertig",
      "cancel": "Abbrechen",
      "retake": "Erneut aufnehmen",
      "filters": "Filter",
      "crop": "Zuschneiden",
      "rotate": "Drehen",

      "failed_to_crop_image": "Zuschneiden des Bildes ist fehlgeschlagen",
      "failed_to_create_document": "Dokument konnte nicht erstellt werden",
      "error_cropping_image": "Fehler beim Zuschneiden des Bildes",
      "error_rotating_image": "Fehler beim Drehen des Bildes",
      "error_applying_filter": "Anwenden des Filters ist fehlgeschlagen",

      "rearrange_results": "Ergebnisse neu anordnen",
      "processing_document": "Dokument wird verarbeitet...",
      "reading_pages": "Dokumentseiten werden gelesen...",
      "rearranging_pdf": "PDF-Seiten werden neu geordnet...",
      "rearranging_docx": "Word-Dokumentseiten werden neu geordnet...",
      "creating_new_file": "Neue Datei wird erstellt...",
      "rearrange_success": "Dokument wurde erfolgreich neu geordnet!",
      "error_occurred": "Ein Fehler ist aufgetreten",
      "try_again": "Erneut versuchen",
      "save": "Speichern",
      "saving": "Speichert...",
      "file_opened": "Die Datei wurde erfolgreich geöffnet!",
      "no_app_to_open": "Keine Anwendung zum Öffnen dieser Dateiformat gefunden.",
      "permission_denied": "Berechtigung zum Öffnen verweigert",
      "file_deleted": "Die Datei wurde erfolgreich gelöscht!",
      "file_renamed": "Die Datei wurde erfolgreich umbenannt!",
      "rearranged_files": "Neu geordnete Dateien",
      "bytes": "Byte",
      "invalid_page_index": "Ungültiger Seitenindex",
      "no_pages_found": "Keine Seiten im Dokument gefunden",
      "empty_file": "Die neue Datei ist leer",
      "file_not_created": "Die Ausgabedatei wurde nicht erstellt",
      "file_not_exist": "Die Datei existiert nicht",

      "error_processing_file": "Fehler bei der Dateiverarbeitung",
      "page_number": "Seite",
      "selected_file": "Ausgewählte Datei",
      "loading_pdf_previews": "PDF-Vorschauen werden geladen",
      "rearrange": "Neu anordnen",

      "rearrange_files": "Dateien neu anordnen",
      "rearrange_pages_in_files": "Seiten in Dateien neu anordnen",
      "select_file": "Datei auswählen",
      "rearrange_file": "Datei neu anordnen",
      "rearrange_file_desc": "Ziehen Sie PDF-Seiten einfach per Drag & Drop und ordnen Sie sie neu an, um Ihr Dokument mühelos zu organisieren.",

      "failed_to_save_file": "Speichern der Datei ist fehlgeschlagen",
      "file_renamed_successfully": "Die Datei wurde erfolgreich umbenannt",
      "error_renaming_file": "Beim Umbenennen ist ein Fehler aufgetreten",
      "no_pages_selected": "Keine Seiten ausgewählt",
      "no_document_available_to_open": "Kein Dokument zum Öffnen vorhanden",
      "file_not_found": "Datei nicht gefunden",
      "cannot_open_file": "Die Datei kann nicht geöffnet werden",
      "zip_file_message": "Dies ist eine ZIP-Datei. Möglicherweise benötigen Sie zum Öffnen ein ZIP-Extraktor.",
      "error_opening_document": "Beim Öffnen des Dokuments ist ein Fehler aufgetreten",

      "error_during_deletion": "Beim Löschen ist ein Fehler aufgetreten",
      "processing_generic_document": "Dokument wird verarbeitet...",
      "error_encountered_fallback": "Ein Fehler ist aufgetreten, Rückfalllösung wird verwendet...",
      "creating_pdf_selected_pages": "PDF mit ausgewählten Seiten wird erstellt...",
      "pdf_created_successfully": "PDF mit ausgewählten Seiten wurde erfolgreich erstellt!",
      "splitting_docx_files": "DOCX Dateien werden in einzelne Dateien geteilt...",
      "creating_zip_archive": "ZIP-Archiv wird erstellt...",
      "zip_created_successfully": "ZIP-Archiv wurde erfolgreich erstellt!",
      "error_saving_original": "Ein Fehler ist aufgetreten. Die Originaldatei wird gespeichert...",


      "edit_files": "Dateien bearbeiten",
      "edit_files_description": "Bearbeiten Sie Ihre Bilder ganz einfach. Laden Sie mehrere Bilder hoch und ändern Sie sie für ein nahtloses Erlebnis.",
      "choose_images": "Bilder auswählen",
      "click_to_choose_images_from_gallery": "Zum Auswählen von Bildern aus der Galerie klicken",
      "next": "Weiter",
      "error_selecting_images": "Fehler beim Auswählen von Bildern",
      "error_capturing_document": "Fehler beim Erfassen des Dokuments",
      "error_processing_files": "Fehler beim Verarbeiten von Dateien",
      "please_select_at_least_one_image": "Bitte wählen Sie mindestens ein Bild aus",
      "image_removed_successfully": "Das Bild wurde erfolgreich entfernt",

      "merged_pdf_file": "PDF-Datei zusammenführen:",

      "merge_results": "Ergebnisse zusammenführen",
      "error_opening_file": "Fehler beim Öffnen der Datei",
      "file_not_found_or_not_processed": "Die Datei wurde nicht gefunden oder ist noch nicht verarbeitet",
      "merge_completed_successfully": "Die PDF Dateien wurden erfolgreich zusammengeführt!",

      "total_files": "Anzahl Dateien",
      'merge_pdfs': 'PDFs zusammenführen',
      'merge_pdf_files': 'PDF-Dateien zusammenführen',
      'merge_file_desc':
      'Führen Sie mühelos PDF-Dateien zusammen für einfacheres Teilen, Speichern und Organisieren.',
      'select_files': 'Dateien auswählen',
      'click_files': 'Klicken Sie, um PDF-Dateien hinzuzufügen',
      'merge_files': 'Dateien zusammenführen',
      'please_two_select': 'Bitte wählen Sie mindestens 2 PDF-Dateien aus',
      'selected_files': 'Ausgewählte Dateien',
      'page_order': 'Seitenreihenfolge',
      'please_select_pdf_only': 'Bitte wählen Sie nur PDF-Dateien aus',
      'error_selecting_pdfs': 'Fehler beim Auswählen der PDFs',
      'failed_to_merge_pdfs': 'Zusammenführen der PDFs fehlgeschlagen',
      'pdf_merger': 'PDF-Zusammenführung',
      'choose_pdf_files': 'PDF-Dateien auswählen',
      'add_more_files': 'Weitere Dateien hinzufügen',
      'remove': 'Entfernen',
      'reorder': 'Neu anordnen',
      'processing': 'Verarbeitung...',
      'merge_complete': 'Zusammenführung abgeschlossen',
      'file_size': 'Dateigröße',
      'total_pages': 'Gesamtseiten',
      'drag_to_reorder': 'Zum Neuanordnen ziehen',
      'no_files_selected': 'Keine Dateien ausgewählt',
      'maximum_files_limit_reached': 'Maximale Anzahl von Dateien erreicht',
      'file_format_not_supported': 'Dateiformat nicht unterstützt',
      'merge_successful': 'Zusammenführung erfolgreich',
      'save_merged_file': 'Zusammengeführte Datei speichern',

      "press_again_to_exit": "Erneut drücken zum Beenden",
          // Menu items
      "rename": "Umbenennen",
      "share": "Teilen",
      "delete": "Löschen",

      // Error messages
      "error_sharing_file": "Fehler beim Teilen der Datei",
      "error_deleting_file": "Fehler beim Löschen der Datei",

      // Dialog titles and content
      "delete_file": "Datei löschen",
      "delete_file_confirmation": "Sind Sie sicher, dass Sie diese Datei löschen wollen?",
      "rename_file": "Datei umbenennen",


      // Share content
      "sharing_document_from_ocr_tool": "Dokument wird aus dem OCR-Tool geteilt",
      "document_from_ocr_tool": "Dokument aus dem OCR-Tool",

      // Validation messages
      "please_enter_valid_name": "Bitte geben Sie einen gültigen Name ein",
      "file_name_already_exists": "Der Dateiname existiert bereits",

      "error_creating_zip_file": "Fehler beim Erstellen einer ZIP-Datei",
      "file_saved_successfully": "Die Datei wurde erfolgreich gespeichert",
      "failed_to_save_file_generic": "Die Datei konnte nicht gespeichert werden",
      "no_files_to_save": "Keine Dateien zum Speichern",
      "all_files_saved_as_zip": "Alle Dateien als ZIP gespeichert",
      "compression_summary": "Zusammenfassung der Komprimierung",
      "file_not_compressed_message": "Die Datei konnte nicht komprimiert werden, weil sie bereits komprimiert ist oder das Format nicht unterstützt wird.",

      "drag_drop": "Ziehen Sie Dateien per Drag-and-Drop herein oder klicken Sie zur Auswahl",
      "compress_file": "Datei komprimieren",
      "reduce_file_size": "Dateigröße reduzieren",
      "reduce_file_size_description": "Reduzieren Sie die Dateigröße von PDFs, Dokumenten und Bildern, ohne die Originalqualität zu beeinträchtigen.",

      "compression_quality": "Komprimierungsqualität",
      "compressing": "Komprimiere...",
      "compress": "Komprimieren",
      "maximum_compression": "Maximale\nKomprimierung",
      "maximum_quality": "Maximale\nQualität",
      "invalid_file_formats": "Ungültige Dateiformate",
      "files_must_be_at_least_mb": "Dateien müssen mindestens 1 MB groß sein",
      "duplicate_files_skipped": "Doppelte Dateien übersprungen",
      "no_valid_files_selected": "Keine gültigen Dateien ausgewählt",
      "some_files_were_skipped": "Einige Dateien wurden übersprungen",
      "duplicates": "Duplikate",
      "rejected_too_small": "abgelehnt (zu klein)",
      "invalid_formats": "ungültige Formate",
      "error_selecting_files": "Fehler beim Auswählen der Dateien",
      "please_select_at_least_one_file": "Bitte wählen Sie zuerst mindestens eine Datei aus",
      "error_compressing_files": "Fehler beim Komprimieren der Dateien",
      "too_small": "zu klein",
      "kilobytes": "KB",
      "megabytes": "MB",
      "file_size_format": "{size} {unit}",


      // File Transfer Screen
      'file_transfer': 'Dateiübertragung',
      'easy_transfer_file': 'Einfache Dateiübertragung',
      'easy_file_transfer_description': 'Dateien sofort übertragen, ohne Qualität, Auflösung oder Klarheit zu verlieren.',
      'choose_file': 'Datei wählen',
      'extract_text': 'Text extrahieren',
      'explore_tools': 'Werkzeuge erkunden',
      'extract_text_description': 'Text nahtlos aus mehreren Bildern oder Dokumenten mit erhöhter Genauigkeit extrahieren.',

      'click_to_choose_files': 'Klicken, um Dateien auszuwählen',
      'completed': 'Abgeschlossen!',
      'please_wait': 'Bitte warten!',

      'file_name': 'Dateiname',
      'single': 'Einzeln',
      'batch': 'Stapel',
      'camera_permission_required': 'Kameraberechtigung ist erforderlich, um den Scanner zu verwenden',
      'no_cameras_found': 'Keine Kameras auf dem Gerät gefunden',
      'camera_initialization_failed': 'Kamera-Initialisierung fehlgeschlagen',
      'camera_permission_not_granted': 'Kameraberechtigung nicht erteilt',
      'grant_camera_permission': 'Kameraberechtigung erteilen',
      'initializing_camera': 'Kamera wird initialisiert...',
      'failed_to_toggle_flash': 'Blitz konnte nicht umgeschaltet werden',

      'select_at_least_one_image': 'Bitte wählen Sie mindestens ein Bild aus',
      'no_text_in_images': 'In den ausgewählten Bildern wurde kein Text erkannt. Versuchen Sie Bilder mit deutlicherem Text',
      'error_processing_images': 'Fehler beim Verarbeiten von Bildern: @error',
      'image_header': '--- Bild @number ---',
      'error_picking_images': 'Fehler beim Auswählen von Bildern: @error',
      'error_preprocessing_image': 'Fehler beim Vorverarbeiten des Bildes: @error',
      'error_in_ocr': 'Fehler bei der Texterkennung (OCR): @error',
      'error_deleting_temp_file': 'Fehler beim Löschen der temporären Datei: @error',


      'pdf_scanner': 'PDF-Scanner',
      'create_your_cv': 'Erstellen Sie Ihren Lebenslauf',
      'ocr': 'Texterkennung (OCR)',
      'merge_file': 'Dateien zusammenführen',
      'edit_file': 'Datei bearbeiten',
      'split_file': 'Datei aufteilen',
      'convert_options': 'Konvertierungsoptionen',
      'convert_pdf': 'PDF konvertieren',
      'convert_image': 'Bild konvertieren',
      'recents': 'Zuletzt verwendet',
      'see_all': 'Alle anzeigen',
      'scan_new': 'Neu scannen',

      'extracted_text_file': 'Extrahierte Textdatei:',
      'no_file_available': 'Keine Datei verfügbar',
      'extracted_text': 'Extrahierter Text:',
      'error_saving_file': 'Fehler beim Speichern der Datei',
      'could_not_open_file': 'Datei konnte nicht geöffnet werden',
      'text_copied_to_clipboard': 'Text in Zwischenablage kopiert',
      'error_copying_text': 'Fehler beim Kopieren des Textes',


      'split': 'Teilen',
      'split_pages': 'Seiten in Datei teilen',
      'split_description': 'Seiten mühelos aus Dateien trennen und dabei Klarheit und Integrität bewahren.',
      'split_document': 'Dokument teilen',

      'notifications_alerts': 'Benachrichtigungen und Warnungen',
      'support_feedback': 'Support und Feedback',
      'privacy_policy': 'Datenschutzrichtlinie',
      'rate_us': 'Bewerten Sie uns',
      'general': 'Allgemein',
      'language': 'Sprache',
      'confidential_documents': 'Vertrauliche Dokumente',
      'code_recovery_options': 'Code-Wiederherstellungsoptionen',
      'email': 'E-Mail',
      'phone_number': 'Telefonnummer',
      'settings': 'Einstellungen',

      'please_select_one_page': 'Bitte wählen Sie mindestens eine Seite aus',
      'split_file_progress_screen': 'Datei aufteilen:',
      'compressed': 'Komprimierte Dateien:',
      'space_saved': 'Gespeicherter Speicherplatz:',
      'total_reduction': 'Gesamte Reduktion:',
      'compress_results': 'Komprimierungsergebnisse',
      'file_delete': 'Datei erfolgreich gelöscht',
      'error_opening_doc': 'Fehler beim Öffnen des Dokuments',
      'drag_and_drop': 'Ziehen und ablegen oder klicken, um Datei auszuwählen',
      'select_only_pdf': 'Bitte nur PDF-, DOC- oder DOCX-Dateien auswählen',
      'rearrange_file_pages': 'Seiten in Dateien neu anordnen',
      'rearrange_file_description': 'Ziehen und ordnen Sie PDF-Seiten mühelos neu, um Ihr Dokument zu organisieren.',
      'error': 'Fehler aufgetreten',
      'processing_doc': 'Dokument wird verarbeitet...',
      'file_does_not_exist': 'Datei existiert nicht',
      'file_empty': 'Datei ist leer',
      'opening_file': 'Datei wird geöffnet:',
      'rearrange_pages': 'Seiten neu anordnen',
      'selected': 'Ausgewählt:',
      'easy_file_transfer': 'Einfacher Dateitransfer',

      //Settings Screen Lines
      'notification_enabled': 'Benachrichtigungen erfolgreich aktiviert',
      'notification_permission': 'Benachrichtigungsberechtigung verweigert',
      'notification_error': 'Fehler beim Aktivieren der Benachrichtigungen',
      'notification_disabled': 'Benachrichtigungen deaktiviert',
      'notification_error_disabled': 'Fehler beim Deaktivieren der Benachrichtigungen',
      'notifications_and_alerts': 'Benachrichtigungen & Alarme',
      'support_and_feedback': 'Support & Feedback',
      'privacy_and_policy': 'Datenschutzrichtlinie',
      'confidential_document': 'Vertrauliche Dokumente',

      //Email Recovery Screen
      "enter_your_email": "Geben Sie Ihre\nE-Mail ein",
      "please_enter_your": "Bitte geben Sie Ihre ",
      "enter": "Eingeben",
      "email_verify": "E-Mail-Verifizierung",
      "enter_email_label": "E-Mail eingeben*",
      "email_hint": "abc@abc.com",
      "enter_email_error": "Bitte geben Sie Ihre E-Mail ein",
      "valid_email_error": "Bitte geben Sie eine gültige E-Mail-Adresse ein",

      //Phone Recovery Screen
      "phone_verify": "Telefonverifizierung",
      "enter_your_phone": "Geben Sie Ihre\nTelefonnummer ein",
      "enter_mobile_label": "Mobilnummer eingeben*",
      "mobile_hint": "01774",
      "enter_phone_error": "Bitte geben Sie Ihre Telefonnummer ein",
      "valid_phone_error": "Bitte geben Sie eine gültige Telefonnummer ein",

      //OTP Screen
      "otp_verify": "OTP-Verifizierung",
      "verify_your_email": "Bestätigen Sie Ihre\nE-Mail",
      "verify_your_phone": "Bestätigen Sie Ihre\nTelefonnummer",
      "enter_code_email": "Geben Sie den Code aus der E-Mail ein, die wir gesendet haben an",
      "enter_code_sms": "Geben Sie den Code aus der SMS ein, die wir gesendet haben an",
      "did_not_receive_code": "Keinen Code erhalten?",
      "resend": "ERNEUT SENDEN",
      "verify": "Verifizieren",
      "otp_verified_successfully": "OTP erfolgreich verifiziert!",

      "compress_files": "Dateien komprimieren",
      "tool_not_implemented": "Tool {toolName} ist noch nicht implementiert",
      "ocr_tool_page": "OCR-Tool-Seite",
      "compress_files_tool_page": "Dateien komprimieren Tool-Seite",
      'norecentdocuments': 'Keine aktuellen Dokumente gefunden',
      'extract_text_from_files': 'Text aus Dateien extrahieren',

    },
  };
}