import 'package:get/get.dart';

class Language extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      // File Transfer Screen
      'file_transfer': 'File Transfer',
      'easy_transfer_file': 'Easy File Transfer',
      'easy_file_transfer_description': 'Transfer files instantly while keeping quality, resolution, and clarity intact.',
      'choose_file': 'Choose File',
      'extract_text': 'Extract Text',
      'explore_tools': 'Explore Tools',

      'pdf_scanner': 'PDF Scanner',
      'create_your_cv': 'Create Your Resume',
      'ocr': 'OCR',
      'compress_file': 'Compress File',
      'merge_file': 'Merge File',
      'edit_file': 'Edit File',
      'split_file': 'Split File',
      'rearrange_file': 'Rearrange File',
      'convert_options': 'Convert Options',
      'convert_pdf': 'Convert PDF',
      'convert_image': 'Convert Image',
      'recents': 'Recents',
      'see_all': 'See All',

      'split': 'Split',
      'split_pages': 'Split Pages In File',
      'split_description': 'Effortlessly separate pages from files while keeping everything clear and intact.',
      'split_document': 'Split Document',

      'notifications_alerts': 'Notifications & Alerts',
      'support_feedback': 'Support & Feedback',
      'privacy_policy': 'Privacy Policy',
      'rate_us': 'Rate Us',
      'share': 'Share',
      'general': 'General',
      'language': 'Language',
      'confidential_documents': 'Confidential Documents',
      'code_recovery_options': 'Code Recovery Options',
      'email': 'Email',
      'phone_number': 'Phone Number',
      'settings': 'Settings',

      'please_select_one_page': 'Please select at least one page',
      'split_file_progress_screen': 'Split File:',
      'reduce_file_size': 'Reduce File Size',
      'reduce_file_size_description': 'Reduce the size of PDFs, documents, and images while preserving original quality.',
      'compress': 'Compress',
      'compressed': 'Compressed Files:',
      'space_saved': 'Space Saved:',
      'total_reduction': 'Total Reductions:',
      'compress_results': 'Compression Results',
      'file_delete': 'File deleted successfully',
      'file_not_found': 'File not found',
      'cannot_open_file': 'Cannot open file:',
      'error_opening_file': 'Error Opening File',
      'error_opening_doc': 'Error opening document',
      'drag_and_drop': 'Drag & Drop or click to choose file',
      'select_only_pdf': 'Please select only PDF, DOC or DOCX files',
      'rearrange_file_pages': 'Rearrange Pages In Files',
      'rearrange_file_description': 'Effortlessly drag and reorder PDF pages to organize your document effortlessly.',
      'rearrange_results': 'Rearrange Results',
      'error': 'Error occurred',
      'processing_doc': 'Processing document...',
      'rearranged_files': 'Rearranged Files...',
      'try_again': 'Try Again',
      'file_does_not_exist': 'File does not exist',
      'file_empty': 'File is empty',
      'opening_file': 'Opening file:',
      'rearrange': 'Rearrange',
      'rearrange_pages': 'Rearrange Pages',
      'selected': 'Selected:',
      'easy_file_transfer': 'Easy Transfer File',

      //new Settings Secreen lines
      'notification_enabled': 'Notifications Enabled Successfully',
      'notification_permission': 'Notification permission denied',
      'notification_error': 'Error enabling notifications',
      'notification_disabled': 'Notifications Disabled',
      'notification_error_disabled': 'Error disabling notifications',
      'notifications_and_alerts': 'Notifications & Alerts',
      'support_and_feedback': 'Support & Feedback',
      'privacy_and_policy': 'Privacy Policy',
      'rate_us': 'Rate Us',
      'share': 'Share',
      'general': 'General',
      'confidential_document': 'Confidential Documents',
      'code_recovery_options': 'Code Recovery Options',
      'email': 'Email',
      'settings': 'Settings',
    },

    'en_GB': {
      // File Transfer Screen
      'file_transfer': 'File Transfer',
      'easy_transfer_file': 'Easy File Transfer',
      'easy_file_transfer_description': 'Transfer files instantly while keeping quality, resolution, and clarity intact.',
      'choose_file': 'Choose File',
      'extract_text': 'Extract Text',
      'explore_tools': 'Explore Tools',


      'pdf_scanner': 'PDF Scanner',
      'create_your_cv': 'Create Your Resume',
      'ocr': 'OCR',
      'compress_file': 'Compress File',
      'merge_file': 'Merge File',
      'edit_file': 'Edit File',
      'split_file': 'Split File',
      'rearrange_file': 'Rearrange File',
      'convert_options': 'Convert Options',
      'convert_pdf': 'Convert PDF',
      'convert_image': 'Convert Image',
      'recents': 'Recents',
      'see_all': 'See All',

      'compress_file': 'Compress File',

      'split': 'Split',
      'split_pages': 'Split Pages In File',
      'split_description': 'Effortlessly separate pages from files while keeping everything clear and intact.',
      'split_document': 'Split Document',

      'notifications_alerts': 'Notifications & Alerts',
      'support_feedback': 'Support & Feedback',
      'privacy_policy': 'Privacy Policy',
      'rate_us': 'Rate Us',
      'share': 'Share',
      'general': 'General',
      'language': 'Language',
      'confidential_documents': 'Confidential Documents',
      'code_recovery_options': 'Code Recovery Options',
      'email': 'Email',
      'phone_number': 'Phone Number',
      'settings': 'Settings',

      'please_select_one_page': 'Please select at least one page',
      'split_file_progress_screen': 'Split File:',
      'reduce_file_size': 'Reduce File Size',
      'reduce_file_size_description': 'Reduce the size of PDFs, documents, and images while preserving original quality.',
      'compress': 'Compress',
      'compressed': 'Compressed Files:',
      'space_saved': 'Space Saved:',
      'total_reduction': 'Total Reductions:',
      'compress_results': 'Compression Results',
      'file_delete': 'File deleted successfully',
      'file_not_found': 'File not found',
      'cannot_open_file': 'Cannot open file:',
      'error_opening_file': 'Error Opening File',
      'error_opening_doc': 'Error opening document',
      'drag_and_drop': 'Drag & Drop or click to choose file',
      'select_only_pdf': 'Please select only PDF, DOC or DOCX files',
      'rearrange_file_pages': 'Rearrange Pages In Files',
      'rearrange_file_description': 'Effortlessly drag and reorder PDF pages to organize your document effortlessly.',
      'rearrange_results': 'Rearrange Results',
      'error': 'Error occurred',
      'processing_doc': 'Processing document...',
      'rearranged_files': 'Rearranged Files...',
      'try_again': 'Try Again',
      'file_does_not_exist': 'File does not exist',
      'file_empty': 'File is empty',
      'opening_file': 'Opening file:',
      'rearrange': 'Rearrange',
      'rearrange_pages': 'Rearrange Pages',
      'selected': 'Selected:',
      'easy_file_transfer': 'Easy Transfer File',

      //Settings Screen Lines
      "notification_enabled": "Notifications enabled successfully",
      "notification_permission": "Notification permission denied",
      "notification_error": "Error enabling notifications",
      "notification_disabled": "Notifications disabled",
      "notification_error_disabled": "Error disabling notifications",
      "notifications_and_alerts": "Notifications & Alerts",
      "support_and_feedback": "Support & Feedback",
      "privacy_and_policy": "Privacy Policy",
      "rate_us": "Rate Us",
      "share": "Share",
      "general": "General",
      "confidential_document": "Confidential Documents",
      "code_recovery_options": "Code Recovery Options",
      "email": "Email",
      "settings": "Settings"
    },

    'ur_PK': {
      // File Transfer Screen
      'file_transfer': 'فائل ٹرانسفر',
      'easy_transfer_file': 'آسان فائل ٹرانسفر',
      'easy_file_transfer_description': 'فائلوں کو فوری طور پر منتقل کریں جبکہ معیار، ریزولوشن اور وضاحت برقرار رکھیں۔',
      'choose_file': 'فائل منتخب کریں',
      'extract_text': 'ٹیکسٹ نکالیں',
      'explore_tools': 'اوزار دریافت کریں',


      'pdf_scanner': 'پی ڈی ایف اسکینر',
      'create_your_cv': 'اپنا سی وی بنائیں',
      'ocr': 'او سی آر',
      'compress_file': 'فائل کو سکیڑیں',
      'merge_file': 'فائلیں ضم کریں',
      'edit_file': 'فائل میں ترمیم کریں',
      'split_file': 'فائل کو تقسیم کریں',
      'rearrange_file': 'فائل کی ترتیب بدلیں',
      'convert_options': 'تبدیلی کے اختیارات',
      'convert_pdf': 'پی ڈی ایف تبدیل کریں',
      'convert_image': 'تصویر تبدیل کریں',
      'recents': 'حالیہ',
      'see_all': 'سب دیکھیں',

      'split': 'تقسیم کریں',
      'split_pages': 'فائل میں صفحات تقسیم کریں',
      'split_description': 'صفحات کو فائلوں سے آسانی سے الگ کریں جبکہ سب کچھ واضح اور برقرار رکھیں۔',
      'split_document': 'دستاویز تقسیم کریں',

      'notifications_alerts': 'اطلاعات اور انتباہات',
      'support_feedback': 'سپورٹ اور فیڈبک',
      'privacy_policy': 'پرائیویسی پالیسی',
      'rate_us': 'ہمیں ریٹ کریں',
      'share': 'شیئر کریں',
      'general': 'عمومی',
      'language': 'زبان',
      'confidential_documents': 'خفیہ دستاویزات',
      'code_recovery_options': 'کوڈ بحالی کے اختیارات',
      'email': 'ای میل',
      'phone_number': 'فون نمبر',
      'settings': 'سیٹنگز',

      'please_select_one_page': 'براہ کرم کم از کم ایک صفحہ منتخب کریں',
      'split_file_progress_screen': 'فائل تقسیم کریں:',
      'reduce_file_size': 'فائل کا سائز کم کریں',
      'reduce_file_size_description': 'پی ڈی ایف، دستاویزات اور تصاویر کا سائز اصل معیار برقرار رکھتے ہوئے کم کریں۔',
      'compress': 'سکیڑیں',
      'compressed': 'کمپریس شدہ فائلیں:',
      'space_saved': 'محفوظ شدہ جگہ:',
      'total_reduction': 'کل کمی:',
      'compress_results': 'کمپریشن کے نتائج',
      'file_delete': 'فائل کامیابی سے حذف ہو گئی',
      'file_not_found': 'فائل نہیں ملی',
      'cannot_open_file': 'فائل کھولی نہیں جا سکتی:',
      'error_opening_file': 'فائل کھولنے میں خرابی',
      'error_opening_doc': 'دستاویز کھولنے میں خرابی',
      'drag_and_drop': 'فائل منتخب کرنے کے لیے ڈریگ کریں یا کلک کریں',
      'select_only_pdf': 'براہ کرم صرف PDF، DOC یا DOCX فائلیں منتخب کریں',
      'rearrange_file_pages': 'فائل کے صفحات دوبارہ ترتیب دیں',
      'rearrange_file_description': 'پی ڈی ایف کے صفحات کو آسانی سے گھسیٹیں اور دوبارہ ترتیب دیں تاکہ آپ کی دستاویز منظم ہو جائے۔',
      'rearrange_results': 'ترتیب نو کے نتائج',
      'error': 'خرابی پیش آگئی',
      'processing_doc': 'دستاویز پر کارروائی ہو رہی ہے...',
      'rearranged_files': 'دوبارہ ترتیب دی گئی فائلیں...',
      'try_again': 'دوبارہ کوشش کریں',
      'file_does_not_exist': 'فائل موجود نہیں',
      'file_empty': 'فائل خالی ہے',
      'opening_file': 'فائل کھولی جا رہی ہے:',
      'rearrange': 'ترتیب دیں',
      'rearrange_pages': 'صفحات کی ترتیب تبدیل کریں',
      'selected': 'منتخب شدہ:',
      'easy_file_transfer': 'آسان فائل ٹرانسفر',

      //Settings Screen Lines
      "notification_enabled": "اطلاعات کامیابی سے فعال ہو گئیں",
      "notification_permission": "اطلاعات کی اجازت مسترد کر دی گئی",
      "notification_error": "اطلاعات کو فعال کرتے وقت خرابی",
      "notification_disabled": "اطلاعات غیر فعال کر دی گئی ہیں",
      "notification_error_disabled": "اطلاعات کو غیر فعال کرتے وقت خرابی",
      "notifications_and_alerts": "اطلاعات اور الرٹس",
      "support_and_feedback": "مدد اور آراء",
      "privacy_and_policy": "رازداری کی پالیسی",
      "rate_us": "ہمیں ریٹنگ دیں",
      "share": "شیئر کریں",
      "general": "عمومی",
      "confidential_document": "خفیہ دستاویزات",
      "code_recovery_options": "کوڈ بازیابی کے اختیارات",
      "email": "ای میل",
      "settings": "ترتیبات"
    },

    'zh_CN': {
      // File Transfer Screen
      'file_transfer': '文件传输',
      'easy_transfer_file': '简易文件传输',
      'easy_file_transfer_description': '即时传输文件，同时保持质量、分辨率和清晰度。',
      'choose_file': '选择文件',
      'extract_text': '提取文本',
      'explore_tools': '探索工具',


      'pdf_scanner': 'PDF扫描仪',
      'create_your_cv': '创建您的简历',
      'ocr': '光学字符识别',
      'compress_file': '压缩文件',
      'merge_file': '合并文件',
      'edit_file': '编辑文件',
      'split_file': '拆分文件',
      'rearrange_file': '重新排列文件',
      'convert_options': '转换选项',
      'convert_pdf': '转换PDF',
      'convert_image': '转换图像',
      'recents': '最近使用',
      'see_all': '查看全部',

      'split': '拆分',
      'split_pages': '拆分文件中的页面',
      'split_description': '轻松从文件中分离页面，同时保持内容清晰完整。',
      'split_document': '拆分文档',

      'notifications_alerts': '通知和提醒',
      'support_feedback': '支持与反馈',
      'privacy_policy': '隐私政策',
      'rate_us': '给我们评分',
      'share': '分享',
      'general': '通用',
      'language': '语言',
      'confidential_documents': '机密文件',
      'code_recovery_options': '代码恢复选项',
      'email': '电子邮件',
      'phone_number': '电话号码',
      'settings': '设置',

      'please_select_one_page': '请至少选择一页',
      'split_file_progress_screen': '拆分文件：',
      'reduce_file_size': '减小文件大小',
      'reduce_file_size_description': '在保留原始质量的同时减小PDF、文档和图像的大小。',
      'compress': '压缩',
      'compressed': '已压缩的文件：',
      'space_saved': '节省空间：',
      'total_reduction': '总减少量：',
      'compress_results': '压缩结果',
      'file_delete': '文件已成功删除',
      'file_not_found': '未找到文件',
      'cannot_open_file': '无法打开文件：',
      'error_opening_file': '打开文件出错',
      'error_opening_doc': '打开文档出错',
      'drag_and_drop': '拖放或点击以选择文件',
      'select_only_pdf': '请选择 PDF、DOC 或 DOCX 文件',
      'rearrange_file_pages': '重新排列文件页面',
      'rearrange_file_description': '轻松拖动和重新排列PDF页面，轻松组织文档。',
      'rearrange_results': '重新排列结果',
      'error': '发生错误',
      'processing_doc': '正在处理文档...',
      'rearranged_files': '已重新排列的文件...',
      'try_again': '再试一次',
      'file_does_not_exist': '文件不存在',
      'file_empty': '文件为空',
      'opening_file': '正在打开文件：',
      'rearrange': '重新排列',
      'rearrange_pages': '重新排列页面',
      'selected': '已选择：',
      'easy_file_transfer': '轻松文件传输',

      //Settings Screen Lines
      "notification_enabled": "通知已成功启用",
      "notification_permission": "通知权限被拒绝",
      "notification_error": "启用通知时出错",
      "notification_disabled": "通知已禁用",
      "notification_error_disabled": "禁用通知时出错",
      "notifications_and_alerts": "通知和提醒",
      "support_and_feedback": "支持与反馈",
      "privacy_and_policy": "隐私政策",
      "rate_us": "评价我们",
      "share": "分享",
      "general": "常规",
      "confidential_document": "机密文件",
      "code_recovery_options": "恢复码选项",
      "email": "电子邮件",
      "settings": "设置"

    },

    'de_DE': {
      // File Transfer Screen
      'file_transfer': 'Dateiübertragung',
      'easy_transfer_file': 'Einfache Dateiübertragung',
      'easy_file_transfer_description': 'Dateien sofort übertragen, ohne Qualität, Auflösung oder Klarheit zu verlieren.',
      'choose_file': 'Datei wählen',
      'extract_text': 'Text extrahieren',
      'explore_tools': 'Werkzeuge erkunden',


      'pdf_scanner': 'PDF-Scanner',
      'create_your_cv': 'Erstellen Sie Ihren Lebenslauf',
      'ocr': 'Texterkennung (OCR)',
      'compress_file': 'Datei komprimieren',
      'merge_file': 'Dateien zusammenführen',
      'edit_file': 'Datei bearbeiten',
      'split_file': 'Datei aufteilen',
      'rearrange_file': 'Datei neu anordnen',
      'convert_options': 'Konvertierungsoptionen',
      'convert_pdf': 'PDF konvertieren',
      'convert_image': 'Bild konvertieren',
      'recents': 'Zuletzt verwendet',
      'see_all': 'Alle anzeigen',

      'split': 'Teilen',
      'split_pages': 'Seiten in Datei teilen',
      'split_description': 'Seiten mühelos aus Dateien trennen und dabei Klarheit und Integrität bewahren.',
      'split_document': 'Dokument teilen',

      'notifications_alerts': 'Benachrichtigungen und Warnungen',
      'support_feedback': 'Support und Feedback',
      'privacy_policy': 'Datenschutzrichtlinie',
      'rate_us': 'Bewerten Sie uns',
      'share': 'Teilen',
      'general': 'Allgemein',
      'language': 'Sprache',
      'confidential_documents': 'Vertrauliche Dokumente',
      'code_recovery_options': 'Code-Wiederherstellungsoptionen',
      'email': 'E-Mail',
      'phone_number': 'Telefonnummer',
      'settings': 'Einstellungen',

      'please_select_one_page': 'Bitte wählen Sie mindestens eine Seite aus',
      'split_file_progress_screen': 'Datei aufteilen:',
      'reduce_file_size': 'Dateigröße reduzieren',
      'reduce_file_size_description': 'Reduzieren Sie die Größe von PDFs, Dokumenten und Bildern, während die Originalqualität erhalten bleibt.',
      'compress': 'Komprimieren',
      'compressed': 'Komprimierte Dateien:',
      'space_saved': 'Gespeicherter Speicherplatz:',
      'total_reduction': 'Gesamte Reduktion:',
      'compress_results': 'Komprimierungsergebnisse',
      'file_delete': 'Datei erfolgreich gelöscht',
      'file_not_found': 'Datei nicht gefunden',
      'cannot_open_file': 'Datei kann nicht geöffnet werden:',
      'error_opening_file': 'Fehler beim Öffnen der Datei',
      'error_opening_doc': 'Fehler beim Öffnen des Dokuments',
      'drag_and_drop': 'Ziehen und ablegen oder klicken, um Datei auszuwählen',
      'select_only_pdf': 'Bitte nur PDF-, DOC- oder DOCX-Dateien auswählen',
      'rearrange_file_pages': 'Seiten in Dateien neu anordnen',
      'rearrange_file_description': 'Ziehen und ordnen Sie PDF-Seiten mühelos neu, um Ihr Dokument zu organisieren.',
      'rearrange_results': 'Ergebnisse neu anordnen',
      'error': 'Fehler aufgetreten',
      'processing_doc': 'Dokument wird verarbeitet...',
      'rearranged_files': 'Neu angeordnete Dateien...',
      'try_again': 'Erneut versuchen',
      'file_does_not_exist': 'Datei existiert nicht',
      'file_empty': 'Datei ist leer',
      'opening_file': 'Datei wird geöffnet:',
      'rearrange': 'Neu anordnen',
      'rearrange_pages': 'Seiten neu anordnen',
      'selected': 'Ausgewählt:',
      'easy_file_transfer': 'Einfacher Dateitransfer',

      //Settings Screen Lines
      'notification_enabled': 'Benachrichtigungen erfolgreich aktiviert',
      'notification_permission': 'Benachrichtigungsberechtigung verweigert',
      'notification_error': 'Fehler beim Aktivieren der Benachrichtigungen',
      'notification_disabled': 'Benachrichtigungen deaktiviert',
      'notification_error_disabled': 'Fehler beim Deaktivieren der Benachrichtigungen',
      'notifications_and_alerts': 'Benachrichtigungen & Alarme',
      'support_and_feedback': 'Support & Feedback',
      'privacy_and_policy': 'Datenschutzrichtlinie',
      'rate_us': 'Bewerten Sie uns',
      'share': 'Teilen',
      'general': 'Allgemein',
      'confidential_document': 'Vertrauliche Dokumente',
      'code_recovery_options': 'Wiederherstellungsoptionen für Codes',
      'email': 'E-Mail',
      'settings': 'Einstellungen'

    },
  };
}